// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package garage

// Generated from OpenAPI doc version v2.1.0 and generator version 2.743.2

import (
	"context"
	"fmt"
	"github.com/guilhem/garage-go/internal/config"
	"github.com/guilhem/garage-go/internal/hooks"
	"github.com/guilhem/garage-go/internal/utils"
	"github.com/guilhem/garage-go/models/components"
	"github.com/guilhem/garage-go/retry"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	// A local server
	"http://localhost:3903/",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// Garage administration API: Administrate your Garage cluster programatically, including status, layout, keys, buckets, and maintainance tasks.
//
// *Disclaimer: This API may change in future Garage versions. Read the changelog and upgrade your scripts before upgrading. Additionnaly, this specification is early stage and can contain bugs, so be careful and please report any issues on our issue tracker.*
type Garage struct {
	SDKVersion       string
	SpecialEndpoints *SpecialEndpoints
	BucketAliases    *BucketAliases
	Permissions      *Permissions
	ClusterLayout    *ClusterLayout
	Buckets          *Buckets
	Clusters         *Clusters
	AdminAPITokens   *AdminAPITokens
	AccessKeys       *AccessKeys
	Nodes            *Nodes
	Blocks           *Blocks
	Bucket           *Bucket
	Cluster          *Cluster
	Workers          *Workers

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*Garage)

// WithServerURL allows the overriding of the default server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *Garage) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *Garage) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *Garage) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *Garage) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(bearerAuth string) SDKOption {
	return func(sdk *Garage) {
		security := components.Security{BearerAuth: &bearerAuth}
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(&security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *Garage) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *Garage) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *Garage) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *Garage {
	sdk := &Garage{
		SDKVersion: "0.2.0",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:  "speakeasy-sdk/go 0.2.0 2.743.2 v2.1.0 github.com/guilhem/garage-go",
			ServerList: ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	if sdk.sdkConfiguration.Security == nil {
		var envVarSecurity components.Security
		if utils.PopulateSecurityFromEnv(&envVarSecurity) {
			sdk.sdkConfiguration.Security = utils.AsSecuritySource(envVarSecurity)
		}
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.SpecialEndpoints = newSpecialEndpoints(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.BucketAliases = newBucketAliases(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Permissions = newPermissions(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.ClusterLayout = newClusterLayout(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Buckets = newBuckets(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Clusters = newClusters(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.AdminAPITokens = newAdminAPITokens(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.AccessKeys = newAccessKeys(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Nodes = newNodes(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Blocks = newBlocks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Bucket = newBucket(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Cluster = newCluster(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Workers = newWorkers(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
