// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type AddBucketAliasResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns exhaustive information about the bucket
	AddBucketAliasResponse *components.AddBucketAliasResponse
}

func (a *AddBucketAliasResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddBucketAliasResponse) GetAddBucketAliasResponse() *components.AddBucketAliasResponse {
	if a == nil {
		return nil
	}
	return a.AddBucketAliasResponse
}
