// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type ApplyClusterLayoutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The updated cluster layout has been applied in the cluster
	ApplyClusterLayoutResponse *components.ApplyClusterLayoutResponse
}

func (a *ApplyClusterLayoutResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *ApplyClusterLayoutResponse) GetApplyClusterLayoutResponse() *components.ApplyClusterLayoutResponse {
	if a == nil {
		return nil
	}
	return a.ApplyClusterLayoutResponse
}
