// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type CheckDomainRequest struct {
	// The domain name to check for
	Domain string `queryParam:"style=form,explode=true,name=domain"`
}

func (c *CheckDomainRequest) GetDomain() string {
	if c == nil {
		return ""
	}
	return c.Domain
}

type CheckDomainResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (c *CheckDomainResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}
