// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type CleanupIncompleteUploadsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The bucket was cleaned up successfully
	CleanupIncompleteUploadsResponse *components.CleanupIncompleteUploadsResponse
}

func (c *CleanupIncompleteUploadsResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CleanupIncompleteUploadsResponse) GetCleanupIncompleteUploadsResponse() *components.CleanupIncompleteUploadsResponse {
	if c == nil {
		return nil
	}
	return c.CleanupIncompleteUploadsResponse
}
