// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type ClusterLayoutSkipDeadNodesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Request has been taken into account
	ClusterLayoutSkipDeadNodesResponse *components.ClusterLayoutSkipDeadNodesResponse
}

func (c *ClusterLayoutSkipDeadNodesResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClusterLayoutSkipDeadNodesResponse) GetClusterLayoutSkipDeadNodesResponse() *components.ClusterLayoutSkipDeadNodesResponse {
	if c == nil {
		return nil
	}
	return c.ClusterLayoutSkipDeadNodesResponse
}
