// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type ConnectClusterNodesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has been handled correctly but it does not mean that all connection requests succeeded; some might have fail, you need to check the body!
	ConnectClusterNodesResponse []components.ConnectNodeResponse
}

func (c *ConnectClusterNodesResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ConnectClusterNodesResponse) GetConnectClusterNodesResponse() []components.ConnectNodeResponse {
	if c == nil {
		return nil
	}
	return c.ConnectClusterNodesResponse
}
