// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type CreateAdminTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Admin token has been created
	CreateAdminTokenResponse *components.CreateAdminTokenResponse
}

func (c *CreateAdminTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateAdminTokenResponse) GetCreateAdminTokenResponse() *components.CreateAdminTokenResponse {
	if c == nil {
		return nil
	}
	return c.CreateAdminTokenResponse
}
