// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type CreateBucketResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns exhaustive information about the bucket
	AddBucketAliasResponse *components.AddBucketAliasResponse
}

func (c *CreateBucketResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateBucketResponse) GetAddBucketAliasResponse() *components.AddBucketAliasResponse {
	if c == nil {
		return nil
	}
	return c.AddBucketAliasResponse
}
