// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type CreateMetadataSnapshotRequest struct {
	// Node ID to query, or `*` for all nodes, or `self` for the node responding to the request
	Node string `queryParam:"style=form,explode=true,name=node"`
}

func (c *CreateMetadataSnapshotRequest) GetNode() string {
	if c == nil {
		return ""
	}
	return c.Node
}

type CreateMetadataSnapshotResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Responses from individual cluster nodes
	MultiResponseLocalCreateMetadataSnapshotResponse *components.MultiResponseLocalCreateMetadataSnapshotResponse
}

func (c *CreateMetadataSnapshotResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateMetadataSnapshotResponse) GetMultiResponseLocalCreateMetadataSnapshotResponse() *components.MultiResponseLocalCreateMetadataSnapshotResponse {
	if c == nil {
		return nil
	}
	return c.MultiResponseLocalCreateMetadataSnapshotResponse
}
