// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type CreateKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Access key has been created
	CreateKeyResponse *components.CreateKeyResponse
}

func (c *CreateKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateKeyResponse) GetCreateKeyResponse() *components.CreateKeyResponse {
	if c == nil {
		return nil
	}
	return c.CreateKeyResponse
}
