// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type DeleteAdminTokenRequest struct {
	// Admin API token ID
	ID string `queryParam:"style=form,explode=true,name=id"`
}

func (d *DeleteAdminTokenRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteAdminTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteAdminTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
