// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type DeleteKeyRequest struct {
	// Access key ID
	ID string `queryParam:"style=form,explode=true,name=id"`
}

func (d *DeleteKeyRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
