// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type DeleteBucketRequest struct {
	// ID of the bucket to delete
	ID string `queryParam:"style=form,explode=true,name=id"`
}

func (d *DeleteBucketRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteBucketResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteBucketResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
