// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type DenyBucketKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns exhaustive information about the bucket
	AddBucketAliasResponse *components.AddBucketAliasResponse
}

func (d *DenyBucketKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DenyBucketKeyResponse) GetAddBucketAliasResponse() *components.AddBucketAliasResponse {
	if d == nil {
		return nil
	}
	return d.AddBucketAliasResponse
}
