// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetAdminTokenInfoRequest struct {
	// Admin API token ID
	ID *string `queryParam:"style=form,explode=true,name=id"`
	// Partial token ID or name to search for
	Search *string `queryParam:"style=form,explode=true,name=search"`
}

func (g *GetAdminTokenInfoRequest) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GetAdminTokenInfoRequest) GetSearch() *string {
	if g == nil {
		return nil
	}
	return g.Search
}

type GetAdminTokenInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Information about the admin token
	GetAdminTokenInfoResponse *components.GetAdminTokenInfoResponse
}

func (g *GetAdminTokenInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAdminTokenInfoResponse) GetGetAdminTokenInfoResponse() *components.GetAdminTokenInfoResponse {
	if g == nil {
		return nil
	}
	return g.GetAdminTokenInfoResponse
}
