// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetBucketInfoRequest struct {
	// Exact bucket ID to look up
	ID *string `queryParam:"style=form,explode=true,name=id"`
	// Global alias of bucket to look up
	GlobalAlias *string `queryParam:"style=form,explode=true,name=globalAlias"`
	// Partial ID or alias to search for
	Search *string `queryParam:"style=form,explode=true,name=search"`
}

func (g *GetBucketInfoRequest) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GetBucketInfoRequest) GetGlobalAlias() *string {
	if g == nil {
		return nil
	}
	return g.GlobalAlias
}

func (g *GetBucketInfoRequest) GetSearch() *string {
	if g == nil {
		return nil
	}
	return g.Search
}

type GetBucketInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns exhaustive information about the bucket
	AddBucketAliasResponse *components.AddBucketAliasResponse
}

func (g *GetBucketInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetBucketInfoResponse) GetAddBucketAliasResponse() *components.AddBucketAliasResponse {
	if g == nil {
		return nil
	}
	return g.AddBucketAliasResponse
}
