// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetBlockInfoRequest struct {
	// Node ID to query, or `*` for all nodes, or `self` for the node responding to the request
	Node                     string                              `queryParam:"style=form,explode=true,name=node"`
	LocalGetBlockInfoRequest components.LocalGetBlockInfoRequest `request:"mediaType=application/json"`
}

func (g *GetBlockInfoRequest) GetNode() string {
	if g == nil {
		return ""
	}
	return g.Node
}

func (g *GetBlockInfoRequest) GetLocalGetBlockInfoRequest() components.LocalGetBlockInfoRequest {
	if g == nil {
		return components.LocalGetBlockInfoRequest{}
	}
	return g.LocalGetBlockInfoRequest
}

type GetBlockInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Detailed block information
	MultiResponseLocalGetBlockInfoResponse *components.MultiResponseLocalGetBlockInfoResponse
}

func (g *GetBlockInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetBlockInfoResponse) GetMultiResponseLocalGetBlockInfoResponse() *components.MultiResponseLocalGetBlockInfoResponse {
	if g == nil {
		return nil
	}
	return g.MultiResponseLocalGetBlockInfoResponse
}
