// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetClusterLayoutHistoryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Cluster layout history
	GetClusterLayoutHistoryResponse *components.GetClusterLayoutHistoryResponse
}

func (g *GetClusterLayoutHistoryResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetClusterLayoutHistoryResponse) GetGetClusterLayoutHistoryResponse() *components.GetClusterLayoutHistoryResponse {
	if g == nil {
		return nil
	}
	return g.GetClusterLayoutHistoryResponse
}
