// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetClusterStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Cluster status report
	GetClusterStatusResponse *components.GetClusterStatusResponse
}

func (g *GetClusterStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetClusterStatusResponse) GetGetClusterStatusResponse() *components.GetClusterStatusResponse {
	if g == nil {
		return nil
	}
	return g.GetClusterStatusResponse
}
