// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetClusterHealthResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Cluster health report
	GetClusterHealthResponse *components.GetClusterHealthResponse
}

func (g *GetClusterHealthResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetClusterHealthResponse) GetGetClusterHealthResponse() *components.GetClusterHealthResponse {
	if g == nil {
		return nil
	}
	return g.GetClusterHealthResponse
}
