// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetClusterStatisticsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Global cluster statistics
	GetClusterStatisticsResponse *components.GetClusterStatisticsResponse
}

func (g *GetClusterStatisticsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetClusterStatisticsResponse) GetGetClusterStatisticsResponse() *components.GetClusterStatisticsResponse {
	if g == nil {
		return nil
	}
	return g.GetClusterStatisticsResponse
}
