// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetClusterLayoutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Current cluster layout
	GetClusterLayoutResponse *components.GetClusterLayoutResponse
}

func (g *GetClusterLayoutResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetClusterLayoutResponse) GetGetClusterLayoutResponse() *components.GetClusterLayoutResponse {
	if g == nil {
		return nil
	}
	return g.GetClusterLayoutResponse
}
