// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetCurrentAdminTokenInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Information about the admin token
	GetAdminTokenInfoResponse *components.GetAdminTokenInfoResponse
}

func (g *GetCurrentAdminTokenInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCurrentAdminTokenInfoResponse) GetGetAdminTokenInfoResponse() *components.GetAdminTokenInfoResponse {
	if g == nil {
		return nil
	}
	return g.GetAdminTokenInfoResponse
}
