// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetKeyInfoRequest struct {
	// Access key ID
	ID *string `queryParam:"style=form,explode=true,name=id"`
	// Partial key ID or name to search for
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// Whether to return the secret access key
	ShowSecretKey *bool `queryParam:"style=form,explode=true,name=showSecretKey"`
}

func (g *GetKeyInfoRequest) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GetKeyInfoRequest) GetSearch() *string {
	if g == nil {
		return nil
	}
	return g.Search
}

func (g *GetKeyInfoRequest) GetShowSecretKey() *bool {
	if g == nil {
		return nil
	}
	return g.ShowSecretKey
}

type GetKeyInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Information about the access key
	CreateKeyResponse *components.CreateKeyResponse
}

func (g *GetKeyInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetKeyInfoResponse) GetCreateKeyResponse() *components.CreateKeyResponse {
	if g == nil {
		return nil
	}
	return g.CreateKeyResponse
}
