// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetNodeStatisticsRequest struct {
	// Node ID to query, or `*` for all nodes, or `self` for the node responding to the request
	Node string `queryParam:"style=form,explode=true,name=node"`
}

func (g *GetNodeStatisticsRequest) GetNode() string {
	if g == nil {
		return ""
	}
	return g.Node
}

type GetNodeStatisticsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Responses from individual cluster nodes
	MultiResponseLocalGetNodeStatisticsResponse *components.MultiResponseLocalGetNodeStatisticsResponse
}

func (g *GetNodeStatisticsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetNodeStatisticsResponse) GetMultiResponseLocalGetNodeStatisticsResponse() *components.MultiResponseLocalGetNodeStatisticsResponse {
	if g == nil {
		return nil
	}
	return g.MultiResponseLocalGetNodeStatisticsResponse
}
