// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetNodeInfoRequest struct {
	// Node ID to query, or `*` for all nodes, or `self` for the node responding to the request
	Node string `queryParam:"style=form,explode=true,name=node"`
}

func (g *GetNodeInfoRequest) GetNode() string {
	if g == nil {
		return ""
	}
	return g.Node
}

type GetNodeInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Responses from individual cluster nodes
	MultiResponseLocalGetNodeInfoResponse *components.MultiResponseLocalGetNodeInfoResponse
}

func (g *GetNodeInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetNodeInfoResponse) GetMultiResponseLocalGetNodeInfoResponse() *components.MultiResponseLocalGetNodeInfoResponse {
	if g == nil {
		return nil
	}
	return g.MultiResponseLocalGetNodeInfoResponse
}
