// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetWorkerInfoRequest struct {
	// Node ID to query, or `*` for all nodes, or `self` for the node responding to the request
	Node                      string                               `queryParam:"style=form,explode=true,name=node"`
	LocalGetWorkerInfoRequest components.LocalGetWorkerInfoRequest `request:"mediaType=application/json"`
}

func (g *GetWorkerInfoRequest) GetNode() string {
	if g == nil {
		return ""
	}
	return g.Node
}

func (g *GetWorkerInfoRequest) GetLocalGetWorkerInfoRequest() components.LocalGetWorkerInfoRequest {
	if g == nil {
		return components.LocalGetWorkerInfoRequest{}
	}
	return g.LocalGetWorkerInfoRequest
}

type GetWorkerInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Responses from individual cluster nodes
	MultiResponseLocalGetWorkerInfoResponse *components.MultiResponseLocalGetWorkerInfoResponse
}

func (g *GetWorkerInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetWorkerInfoResponse) GetMultiResponseLocalGetWorkerInfoResponse() *components.MultiResponseLocalGetWorkerInfoResponse {
	if g == nil {
		return nil
	}
	return g.MultiResponseLocalGetWorkerInfoResponse
}
