// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type GetWorkerVariableRequest struct {
	// Node ID to query, or `*` for all nodes, or `self` for the node responding to the request
	Node                          string                                   `queryParam:"style=form,explode=true,name=node"`
	LocalGetWorkerVariableRequest components.LocalGetWorkerVariableRequest `request:"mediaType=application/json"`
}

func (g *GetWorkerVariableRequest) GetNode() string {
	if g == nil {
		return ""
	}
	return g.Node
}

func (g *GetWorkerVariableRequest) GetLocalGetWorkerVariableRequest() components.LocalGetWorkerVariableRequest {
	if g == nil {
		return components.LocalGetWorkerVariableRequest{}
	}
	return g.LocalGetWorkerVariableRequest
}

type GetWorkerVariableResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Responses from individual cluster nodes
	MultiResponseLocalGetWorkerVariableResponse *components.MultiResponseLocalGetWorkerVariableResponse
}

func (g *GetWorkerVariableResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetWorkerVariableResponse) GetMultiResponseLocalGetWorkerVariableResponse() *components.MultiResponseLocalGetWorkerVariableResponse {
	if g == nil {
		return nil
	}
	return g.MultiResponseLocalGetWorkerVariableResponse
}
