// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type ImportKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Access key has been imported
	CreateKeyResponse *components.CreateKeyResponse
}

func (i *ImportKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *ImportKeyResponse) GetCreateKeyResponse() *components.CreateKeyResponse {
	if i == nil {
		return nil
	}
	return i.CreateKeyResponse
}
