// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type InspectObjectRequest struct {
	BucketID string `queryParam:"style=form,explode=true,name=bucketId"`
	Key      string `queryParam:"style=form,explode=true,name=key"`
}

func (i *InspectObjectRequest) GetBucketID() string {
	if i == nil {
		return ""
	}
	return i.BucketID
}

func (i *InspectObjectRequest) GetKey() string {
	if i == nil {
		return ""
	}
	return i.Key
}

type InspectObjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns exhaustive information about the object
	InspectObjectResponse *components.InspectObjectResponse
}

func (i *InspectObjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InspectObjectResponse) GetInspectObjectResponse() *components.InspectObjectResponse {
	if i == nil {
		return nil
	}
	return i.InspectObjectResponse
}
