// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type LaunchRepairOperationRequest struct {
	// Node ID to query, or `*` for all nodes, or `self` for the node responding to the request
	Node                              string                                       `queryParam:"style=form,explode=true,name=node"`
	LocalLaunchRepairOperationRequest components.LocalLaunchRepairOperationRequest `request:"mediaType=application/json"`
}

func (l *LaunchRepairOperationRequest) GetNode() string {
	if l == nil {
		return ""
	}
	return l.Node
}

func (l *LaunchRepairOperationRequest) GetLocalLaunchRepairOperationRequest() components.LocalLaunchRepairOperationRequest {
	if l == nil {
		return components.LocalLaunchRepairOperationRequest{}
	}
	return l.LocalLaunchRepairOperationRequest
}

type LaunchRepairOperationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Responses from individual cluster nodes
	MultiResponseLocalLaunchRepairOperationResponse *components.MultiResponseLocalLaunchRepairOperationResponse
}

func (l *LaunchRepairOperationResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *LaunchRepairOperationResponse) GetMultiResponseLocalLaunchRepairOperationResponse() *components.MultiResponseLocalLaunchRepairOperationResponse {
	if l == nil {
		return nil
	}
	return l.MultiResponseLocalLaunchRepairOperationResponse
}
