// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type ListBucketsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns the UUID of all the buckets and all their aliases
	ListBucketsResponse []components.ListBucketsResponseItem
}

func (l *ListBucketsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListBucketsResponse) GetListBucketsResponse() []components.ListBucketsResponseItem {
	if l == nil {
		return nil
	}
	return l.ListBucketsResponse
}
