// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type ListBlockErrorsRequest struct {
	// Node ID to query, or `*` for all nodes, or `self` for the node responding to the request
	Node string `queryParam:"style=form,explode=true,name=node"`
}

func (l *ListBlockErrorsRequest) GetNode() string {
	if l == nil {
		return ""
	}
	return l.Node
}

type ListBlockErrorsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Responses from individual cluster nodes
	MultiResponseLocalListBlockErrorsResponse *components.MultiResponseLocalListBlockErrorsResponse
}

func (l *ListBlockErrorsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListBlockErrorsResponse) GetMultiResponseLocalListBlockErrorsResponse() *components.MultiResponseLocalListBlockErrorsResponse {
	if l == nil {
		return nil
	}
	return l.MultiResponseLocalListBlockErrorsResponse
}
