// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type ListAdminTokensResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns info about all admin API tokens
	ListAdminTokensResponse []components.GetAdminTokenInfoResponse
}

func (l *ListAdminTokensResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAdminTokensResponse) GetListAdminTokensResponse() []components.GetAdminTokenInfoResponse {
	if l == nil {
		return nil
	}
	return l.ListAdminTokensResponse
}
