// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type ListKeysResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns the key identifier (aka `AWS_ACCESS_KEY_ID`) and its associated, human friendly, name if any (otherwise return an empty string)
	ListKeysResponse []components.ListKeysResponseItem
}

func (l *ListKeysResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListKeysResponse) GetListKeysResponse() []components.ListKeysResponseItem {
	if l == nil {
		return nil
	}
	return l.ListKeysResponse
}
