// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type ListWorkersRequest struct {
	// Node ID to query, or `*` for all nodes, or `self` for the node responding to the request
	Node                    string                             `queryParam:"style=form,explode=true,name=node"`
	LocalListWorkersRequest components.LocalListWorkersRequest `request:"mediaType=application/json"`
}

func (l *ListWorkersRequest) GetNode() string {
	if l == nil {
		return ""
	}
	return l.Node
}

func (l *ListWorkersRequest) GetLocalListWorkersRequest() components.LocalListWorkersRequest {
	if l == nil {
		return components.LocalListWorkersRequest{}
	}
	return l.LocalListWorkersRequest
}

type ListWorkersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Responses from individual cluster nodes
	MultiResponseLocalListWorkersResponse *components.MultiResponseLocalListWorkersResponse
}

func (l *ListWorkersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListWorkersResponse) GetMultiResponseLocalListWorkersResponse() *components.MultiResponseLocalListWorkersResponse {
	if l == nil {
		return nil
	}
	return l.MultiResponseLocalListWorkersResponse
}
