// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type MetricsSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization,env=garage_bearer_auth"`
}

func (m *MetricsSecurity) GetBearerAuth() *string {
	if m == nil {
		return nil
	}
	return m.BearerAuth
}

type MetricsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (m *MetricsResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}
