// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type PreviewClusterLayoutChangesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Information about the new layout
	PreviewClusterLayoutChangesResponse *components.PreviewClusterLayoutChangesResponseUnion
}

func (p *PreviewClusterLayoutChangesResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PreviewClusterLayoutChangesResponse) GetPreviewClusterLayoutChangesResponse() *components.PreviewClusterLayoutChangesResponseUnion {
	if p == nil {
		return nil
	}
	return p.PreviewClusterLayoutChangesResponse
}
