// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type PurgeBlocksRequest struct {
	// Node ID to query, or `*` for all nodes, or `self` for the node responding to the request
	Node        string   `queryParam:"style=form,explode=true,name=node"`
	RequestBody []string `request:"mediaType=application/json"`
}

func (p *PurgeBlocksRequest) GetNode() string {
	if p == nil {
		return ""
	}
	return p.Node
}

func (p *PurgeBlocksRequest) GetRequestBody() []string {
	if p == nil {
		return []string{}
	}
	return p.RequestBody
}

type PurgeBlocksResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Responses from individual cluster nodes
	MultiResponseLocalPurgeBlocksResponse *components.MultiResponseLocalPurgeBlocksResponse
}

func (p *PurgeBlocksResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PurgeBlocksResponse) GetMultiResponseLocalPurgeBlocksResponse() *components.MultiResponseLocalPurgeBlocksResponse {
	if p == nil {
		return nil
	}
	return p.MultiResponseLocalPurgeBlocksResponse
}
