// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type RemoveBucketAliasResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns exhaustive information about the bucket
	AddBucketAliasResponse *components.AddBucketAliasResponse
}

func (r *RemoveBucketAliasResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RemoveBucketAliasResponse) GetAddBucketAliasResponse() *components.AddBucketAliasResponse {
	if r == nil {
		return nil
	}
	return r.AddBucketAliasResponse
}
