// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type RetryBlockResyncRequest struct {
	// Node ID to query, or `*` for all nodes, or `self` for the node responding to the request
	Node                         string                                       `queryParam:"style=form,explode=true,name=node"`
	LocalRetryBlockResyncRequest components.LocalRetryBlockResyncRequestUnion `request:"mediaType=application/json"`
}

func (r *RetryBlockResyncRequest) GetNode() string {
	if r == nil {
		return ""
	}
	return r.Node
}

func (r *RetryBlockResyncRequest) GetLocalRetryBlockResyncRequest() components.LocalRetryBlockResyncRequestUnion {
	if r == nil {
		return components.LocalRetryBlockResyncRequestUnion{}
	}
	return r.LocalRetryBlockResyncRequest
}

type RetryBlockResyncResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Responses from individual cluster nodes
	MultiResponseLocalRetryBlockResyncResponse *components.MultiResponseLocalRetryBlockResyncResponse
}

func (r *RetryBlockResyncResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RetryBlockResyncResponse) GetMultiResponseLocalRetryBlockResyncResponse() *components.MultiResponseLocalRetryBlockResyncResponse {
	if r == nil {
		return nil
	}
	return r.MultiResponseLocalRetryBlockResyncResponse
}
