// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type RevertClusterLayoutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// All pending changes to the cluster layout have been erased
	GetClusterLayoutResponse *components.GetClusterLayoutResponse
}

func (r *RevertClusterLayoutResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RevertClusterLayoutResponse) GetGetClusterLayoutResponse() *components.GetClusterLayoutResponse {
	if r == nil {
		return nil
	}
	return r.GetClusterLayoutResponse
}
