// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type SetWorkerVariableRequest struct {
	// Node ID to query, or `*` for all nodes, or `self` for the node responding to the request
	Node                          string                                   `queryParam:"style=form,explode=true,name=node"`
	LocalSetWorkerVariableRequest components.LocalSetWorkerVariableRequest `request:"mediaType=application/json"`
}

func (s *SetWorkerVariableRequest) GetNode() string {
	if s == nil {
		return ""
	}
	return s.Node
}

func (s *SetWorkerVariableRequest) GetLocalSetWorkerVariableRequest() components.LocalSetWorkerVariableRequest {
	if s == nil {
		return components.LocalSetWorkerVariableRequest{}
	}
	return s.LocalSetWorkerVariableRequest
}

type SetWorkerVariableResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Responses from individual cluster nodes
	MultiResponseLocalSetWorkerVariableResponse *components.MultiResponseLocalSetWorkerVariableResponse
}

func (s *SetWorkerVariableResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SetWorkerVariableResponse) GetMultiResponseLocalSetWorkerVariableResponse() *components.MultiResponseLocalSetWorkerVariableResponse {
	if s == nil {
		return nil
	}
	return s.MultiResponseLocalSetWorkerVariableResponse
}
