// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type UpdateBucketRequest struct {
	// ID of the bucket to update
	ID                      string                             `queryParam:"style=form,explode=true,name=id"`
	UpdateBucketRequestBody components.UpdateBucketRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateBucketRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateBucketRequest) GetUpdateBucketRequestBody() components.UpdateBucketRequestBody {
	if u == nil {
		return components.UpdateBucketRequestBody{}
	}
	return u.UpdateBucketRequestBody
}

type UpdateBucketResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Bucket has been updated
	AddBucketAliasResponse *components.AddBucketAliasResponse
}

func (u *UpdateBucketResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateBucketResponse) GetAddBucketAliasResponse() *components.AddBucketAliasResponse {
	if u == nil {
		return nil
	}
	return u.AddBucketAliasResponse
}
