// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type UpdateAdminTokenRequest struct {
	// Admin API token ID
	ID                          string                                 `queryParam:"style=form,explode=true,name=id"`
	UpdateAdminTokenRequestBody components.UpdateAdminTokenRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateAdminTokenRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateAdminTokenRequest) GetUpdateAdminTokenRequestBody() components.UpdateAdminTokenRequestBody {
	if u == nil {
		return components.UpdateAdminTokenRequestBody{}
	}
	return u.UpdateAdminTokenRequestBody
}

type UpdateAdminTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Admin token has been updated
	GetAdminTokenInfoResponse *components.GetAdminTokenInfoResponse
}

func (u *UpdateAdminTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateAdminTokenResponse) GetGetAdminTokenInfoResponse() *components.GetAdminTokenInfoResponse {
	if u == nil {
		return nil
	}
	return u.GetAdminTokenInfoResponse
}
