// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type UpdateKeyRequest struct {
	// Access key ID
	ID               string                      `queryParam:"style=form,explode=true,name=id"`
	CreateKeyRequest components.CreateKeyRequest `request:"mediaType=application/json"`
}

func (u *UpdateKeyRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateKeyRequest) GetCreateKeyRequest() components.CreateKeyRequest {
	if u == nil {
		return components.CreateKeyRequest{}
	}
	return u.CreateKeyRequest
}

type UpdateKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Access key has been updated
	CreateKeyResponse *components.CreateKeyResponse
}

func (u *UpdateKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateKeyResponse) GetCreateKeyResponse() *components.CreateKeyResponse {
	if u == nil {
		return nil
	}
	return u.CreateKeyResponse
}
