// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/guilhem/garage-go/models/components"
)

type UpdateClusterLayoutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Proposed changes have been added to the list of pending changes
	GetClusterLayoutResponse *components.GetClusterLayoutResponse
}

func (u *UpdateClusterLayoutResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateClusterLayoutResponse) GetGetClusterLayoutResponse() *components.GetClusterLayoutResponse {
	if u == nil {
		return nil
	}
	return u.GetClusterLayoutResponse
}
