// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/internal/utils"
	"github.com/guilhem/garage-go/optionalnullable"
	"time"
)

type AddBucketAliasResponse struct {
	// Total number of bytes used by objects in this bucket
	Bytes int64 `json:"bytes"`
	// Bucket creation date
	Created time.Time `json:"created"`
	// List of global aliases for this bucket
	GlobalAliases []string `json:"globalAliases"`
	// Identifier of the bucket
	ID string `json:"id"`
	// List of access keys that have permissions granted on this bucket
	Keys []GetBucketInfoKey `json:"keys"`
	// Number of objects in this bucket
	Objects int64           `json:"objects"`
	Quotas  APIBucketQuotas `json:"quotas"`
	// Total number of bytes used by unfinished multipart uploads in this bucket
	UnfinishedMultipartUploadBytes int64 `json:"unfinishedMultipartUploadBytes"`
	// Number of parts in unfinished multipart uploads in this bucket
	UnfinishedMultipartUploadParts int64 `json:"unfinishedMultipartUploadParts"`
	// Number of unfinished multipart uploads in this bucket
	UnfinishedMultipartUploads int64 `json:"unfinishedMultipartUploads"`
	// Number of unfinished uploads in this bucket
	UnfinishedUploads int64 `json:"unfinishedUploads"`
	// Whether website acces is enabled for this bucket
	WebsiteAccess bool                                                            `json:"websiteAccess"`
	WebsiteConfig optionalnullable.OptionalNullable[GetBucketInfoWebsiteResponse] `json:"websiteConfig,omitempty"`
}

func (a AddBucketAliasResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddBucketAliasResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"bytes", "created", "globalAliases", "id", "keys", "objects", "quotas", "unfinishedMultipartUploadBytes", "unfinishedMultipartUploadParts", "unfinishedMultipartUploads", "unfinishedUploads", "websiteAccess"}); err != nil {
		return err
	}
	return nil
}

func (a *AddBucketAliasResponse) GetBytes() int64 {
	if a == nil {
		return 0
	}
	return a.Bytes
}

func (a *AddBucketAliasResponse) GetCreated() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.Created
}

func (a *AddBucketAliasResponse) GetGlobalAliases() []string {
	if a == nil {
		return []string{}
	}
	return a.GlobalAliases
}

func (a *AddBucketAliasResponse) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AddBucketAliasResponse) GetKeys() []GetBucketInfoKey {
	if a == nil {
		return []GetBucketInfoKey{}
	}
	return a.Keys
}

func (a *AddBucketAliasResponse) GetObjects() int64 {
	if a == nil {
		return 0
	}
	return a.Objects
}

func (a *AddBucketAliasResponse) GetQuotas() APIBucketQuotas {
	if a == nil {
		return APIBucketQuotas{}
	}
	return a.Quotas
}

func (a *AddBucketAliasResponse) GetUnfinishedMultipartUploadBytes() int64 {
	if a == nil {
		return 0
	}
	return a.UnfinishedMultipartUploadBytes
}

func (a *AddBucketAliasResponse) GetUnfinishedMultipartUploadParts() int64 {
	if a == nil {
		return 0
	}
	return a.UnfinishedMultipartUploadParts
}

func (a *AddBucketAliasResponse) GetUnfinishedMultipartUploads() int64 {
	if a == nil {
		return 0
	}
	return a.UnfinishedMultipartUploads
}

func (a *AddBucketAliasResponse) GetUnfinishedUploads() int64 {
	if a == nil {
		return 0
	}
	return a.UnfinishedUploads
}

func (a *AddBucketAliasResponse) GetWebsiteAccess() bool {
	if a == nil {
		return false
	}
	return a.WebsiteAccess
}

func (a *AddBucketAliasResponse) GetWebsiteConfig() optionalnullable.OptionalNullable[GetBucketInfoWebsiteResponse] {
	if a == nil {
		return nil
	}
	return a.WebsiteConfig
}
