// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/guilhem/garage-go/internal/utils"
)

type AddBucketAliasRequest2 struct {
	AccessKeyID string `json:"accessKeyId"`
	LocalAlias  string `json:"localAlias"`
	BucketID    string `json:"bucketId"`
}

func (a AddBucketAliasRequest2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddBucketAliasRequest2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"accessKeyId", "localAlias", "bucketId"}); err != nil {
		return err
	}
	return nil
}

func (a *AddBucketAliasRequest2) GetAccessKeyID() string {
	if a == nil {
		return ""
	}
	return a.AccessKeyID
}

func (a *AddBucketAliasRequest2) GetLocalAlias() string {
	if a == nil {
		return ""
	}
	return a.LocalAlias
}

func (a *AddBucketAliasRequest2) GetBucketID() string {
	if a == nil {
		return ""
	}
	return a.BucketID
}

type AddBucketAliasRequest1 struct {
	GlobalAlias string `json:"globalAlias"`
	BucketID    string `json:"bucketId"`
}

func (a AddBucketAliasRequest1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddBucketAliasRequest1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"globalAlias", "bucketId"}); err != nil {
		return err
	}
	return nil
}

func (a *AddBucketAliasRequest1) GetGlobalAlias() string {
	if a == nil {
		return ""
	}
	return a.GlobalAlias
}

func (a *AddBucketAliasRequest1) GetBucketID() string {
	if a == nil {
		return ""
	}
	return a.BucketID
}

type AddBucketAliasRequestUnionType string

const (
	AddBucketAliasRequestUnionTypeAddBucketAliasRequest1 AddBucketAliasRequestUnionType = "AddBucketAliasRequest_1"
	AddBucketAliasRequestUnionTypeAddBucketAliasRequest2 AddBucketAliasRequestUnionType = "AddBucketAliasRequest_2"
)

type AddBucketAliasRequestUnion struct {
	AddBucketAliasRequest1 *AddBucketAliasRequest1 `queryParam:"inline,name=AddBucketAliasRequest"`
	AddBucketAliasRequest2 *AddBucketAliasRequest2 `queryParam:"inline,name=AddBucketAliasRequest"`

	Type AddBucketAliasRequestUnionType
}

func CreateAddBucketAliasRequestUnionAddBucketAliasRequest1(addBucketAliasRequest1 AddBucketAliasRequest1) AddBucketAliasRequestUnion {
	typ := AddBucketAliasRequestUnionTypeAddBucketAliasRequest1

	return AddBucketAliasRequestUnion{
		AddBucketAliasRequest1: &addBucketAliasRequest1,
		Type:                   typ,
	}
}

func CreateAddBucketAliasRequestUnionAddBucketAliasRequest2(addBucketAliasRequest2 AddBucketAliasRequest2) AddBucketAliasRequestUnion {
	typ := AddBucketAliasRequestUnionTypeAddBucketAliasRequest2

	return AddBucketAliasRequestUnion{
		AddBucketAliasRequest2: &addBucketAliasRequest2,
		Type:                   typ,
	}
}

func (u *AddBucketAliasRequestUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var addBucketAliasRequest2 AddBucketAliasRequest2 = AddBucketAliasRequest2{}
	if err := utils.UnmarshalJSON(data, &addBucketAliasRequest2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AddBucketAliasRequestUnionTypeAddBucketAliasRequest2,
			Value: &addBucketAliasRequest2,
		})
	}

	var addBucketAliasRequest1 AddBucketAliasRequest1 = AddBucketAliasRequest1{}
	if err := utils.UnmarshalJSON(data, &addBucketAliasRequest1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AddBucketAliasRequestUnionTypeAddBucketAliasRequest1,
			Value: &addBucketAliasRequest1,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for AddBucketAliasRequestUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for AddBucketAliasRequestUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(AddBucketAliasRequestUnionType)
	switch best.Type {
	case AddBucketAliasRequestUnionTypeAddBucketAliasRequest2:
		u.AddBucketAliasRequest2 = best.Value.(*AddBucketAliasRequest2)
		return nil
	case AddBucketAliasRequestUnionTypeAddBucketAliasRequest1:
		u.AddBucketAliasRequest1 = best.Value.(*AddBucketAliasRequest1)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AddBucketAliasRequestUnion", string(data))
}

func (u AddBucketAliasRequestUnion) MarshalJSON() ([]byte, error) {
	if u.AddBucketAliasRequest1 != nil {
		return utils.MarshalJSON(u.AddBucketAliasRequest1, "", true)
	}

	if u.AddBucketAliasRequest2 != nil {
		return utils.MarshalJSON(u.AddBucketAliasRequest2, "", true)
	}

	return nil, errors.New("could not marshal union type AddBucketAliasRequestUnion: all fields are null")
}
