// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AllowBucketKeyRequest struct {
	AccessKeyID string           `json:"accessKeyId"`
	BucketID    string           `json:"bucketId"`
	Permissions APIBucketKeyPerm `json:"permissions"`
}

func (a *AllowBucketKeyRequest) GetAccessKeyID() string {
	if a == nil {
		return ""
	}
	return a.AccessKeyID
}

func (a *AllowBucketKeyRequest) GetBucketID() string {
	if a == nil {
		return ""
	}
	return a.BucketID
}

func (a *AllowBucketKeyRequest) GetPermissions() APIBucketKeyPerm {
	if a == nil {
		return APIBucketKeyPerm{}
	}
	return a.Permissions
}
