// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type APIBucketKeyPerm struct {
	Owner *bool `json:"owner,omitempty"`
	Read  *bool `json:"read,omitempty"`
	Write *bool `json:"write,omitempty"`
}

func (a *APIBucketKeyPerm) GetOwner() *bool {
	if a == nil {
		return nil
	}
	return a.Owner
}

func (a *APIBucketKeyPerm) GetRead() *bool {
	if a == nil {
		return nil
	}
	return a.Read
}

func (a *APIBucketKeyPerm) GetWrite() *bool {
	if a == nil {
		return nil
	}
	return a.Write
}
