// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type APIBucketQuotas struct {
	MaxObjects optionalnullable.OptionalNullable[int64] `json:"maxObjects,omitempty"`
	MaxSize    optionalnullable.OptionalNullable[int64] `json:"maxSize,omitempty"`
}

func (a *APIBucketQuotas) GetMaxObjects() optionalnullable.OptionalNullable[int64] {
	if a == nil {
		return nil
	}
	return a.MaxObjects
}

func (a *APIBucketQuotas) GetMaxSize() optionalnullable.OptionalNullable[int64] {
	if a == nil {
		return nil
	}
	return a.MaxSize
}
