// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ApplyClusterLayoutResponse struct {
	Layout GetClusterLayoutResponse `json:"layout"`
	// Plain-text information about the layout computation
	// (do not try to parse this)
	Message []string `json:"message"`
}

func (a *ApplyClusterLayoutResponse) GetLayout() GetClusterLayoutResponse {
	if a == nil {
		return GetClusterLayoutResponse{}
	}
	return a.Layout
}

func (a *ApplyClusterLayoutResponse) GetMessage() []string {
	if a == nil {
		return []string{}
	}
	return a.Message
}
