// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ApplyClusterLayoutRequest struct {
	// As a safety measure, the new version number of the layout must
	// be specified here
	Version int64 `json:"version"`
}

func (a *ApplyClusterLayoutRequest) GetVersion() int64 {
	if a == nil {
		return 0
	}
	return a.Version
}
