// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type BlockVersion struct {
	Backlink         optionalnullable.OptionalNullable[BlockVersionBacklinkUnion] `json:"backlink,omitempty"`
	GarbageCollected bool                                                         `json:"garbageCollected"`
	RefDeleted       bool                                                         `json:"refDeleted"`
	VersionDeleted   bool                                                         `json:"versionDeleted"`
	VersionID        string                                                       `json:"versionId"`
}

func (b *BlockVersion) GetBacklink() optionalnullable.OptionalNullable[BlockVersionBacklinkUnion] {
	if b == nil {
		return nil
	}
	return b.Backlink
}

func (b *BlockVersion) GetGarbageCollected() bool {
	if b == nil {
		return false
	}
	return b.GarbageCollected
}

func (b *BlockVersion) GetRefDeleted() bool {
	if b == nil {
		return false
	}
	return b.RefDeleted
}

func (b *BlockVersion) GetVersionDeleted() bool {
	if b == nil {
		return false
	}
	return b.VersionDeleted
}

func (b *BlockVersion) GetVersionID() string {
	if b == nil {
		return ""
	}
	return b.VersionID
}
