// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BlockError struct {
	BlockHash      string `json:"blockHash"`
	ErrorCount     int64  `json:"errorCount"`
	LastTrySecsAgo int64  `json:"lastTrySecsAgo"`
	NextTryInSecs  int64  `json:"nextTryInSecs"`
	Refcount       int64  `json:"refcount"`
}

func (b *BlockError) GetBlockHash() string {
	if b == nil {
		return ""
	}
	return b.BlockHash
}

func (b *BlockError) GetErrorCount() int64 {
	if b == nil {
		return 0
	}
	return b.ErrorCount
}

func (b *BlockError) GetLastTrySecsAgo() int64 {
	if b == nil {
		return 0
	}
	return b.LastTrySecsAgo
}

func (b *BlockError) GetNextTryInSecs() int64 {
	if b == nil {
		return 0
	}
	return b.NextTryInSecs
}

func (b *BlockError) GetRefcount() int64 {
	if b == nil {
		return 0
	}
	return b.Refcount
}
