// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/guilhem/garage-go/internal/utils"
	"github.com/guilhem/garage-go/optionalnullable"
)

type Upload struct {
	BucketID               optionalnullable.OptionalNullable[string] `json:"bucketId,omitempty"`
	Key                    optionalnullable.OptionalNullable[string] `json:"key,omitempty"`
	UploadDeleted          bool                                      `json:"uploadDeleted"`
	UploadGarbageCollected bool                                      `json:"uploadGarbageCollected"`
	UploadID               string                                    `json:"uploadId"`
}

func (u Upload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *Upload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"uploadDeleted", "uploadGarbageCollected", "uploadId"}); err != nil {
		return err
	}
	return nil
}

func (u *Upload) GetBucketID() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.BucketID
}

func (u *Upload) GetKey() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Key
}

func (u *Upload) GetUploadDeleted() bool {
	if u == nil {
		return false
	}
	return u.UploadDeleted
}

func (u *Upload) GetUploadGarbageCollected() bool {
	if u == nil {
		return false
	}
	return u.UploadGarbageCollected
}

func (u *Upload) GetUploadID() string {
	if u == nil {
		return ""
	}
	return u.UploadID
}

type BlockVersionBacklink2 struct {
	Upload Upload `json:"upload"`
}

func (b BlockVersionBacklink2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BlockVersionBacklink2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"upload"}); err != nil {
		return err
	}
	return nil
}

func (b *BlockVersionBacklink2) GetUpload() Upload {
	if b == nil {
		return Upload{}
	}
	return b.Upload
}

type Object struct {
	BucketID string `json:"bucketId"`
	Key      string `json:"key"`
}

func (o Object) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *Object) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, []string{"bucketId", "key"}); err != nil {
		return err
	}
	return nil
}

func (o *Object) GetBucketID() string {
	if o == nil {
		return ""
	}
	return o.BucketID
}

func (o *Object) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

type BlockVersionBacklink1 struct {
	Object Object `json:"object"`
}

func (b BlockVersionBacklink1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BlockVersionBacklink1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"object"}); err != nil {
		return err
	}
	return nil
}

func (b *BlockVersionBacklink1) GetObject() Object {
	if b == nil {
		return Object{}
	}
	return b.Object
}

type BlockVersionBacklinkUnionType string

const (
	BlockVersionBacklinkUnionTypeBlockVersionBacklink1 BlockVersionBacklinkUnionType = "BlockVersionBacklink_1"
	BlockVersionBacklinkUnionTypeBlockVersionBacklink2 BlockVersionBacklinkUnionType = "BlockVersionBacklink_2"
)

type BlockVersionBacklinkUnion struct {
	BlockVersionBacklink1 *BlockVersionBacklink1 `queryParam:"inline,name=BlockVersionBacklink"`
	BlockVersionBacklink2 *BlockVersionBacklink2 `queryParam:"inline,name=BlockVersionBacklink"`

	Type BlockVersionBacklinkUnionType
}

func CreateBlockVersionBacklinkUnionBlockVersionBacklink1(blockVersionBacklink1 BlockVersionBacklink1) BlockVersionBacklinkUnion {
	typ := BlockVersionBacklinkUnionTypeBlockVersionBacklink1

	return BlockVersionBacklinkUnion{
		BlockVersionBacklink1: &blockVersionBacklink1,
		Type:                  typ,
	}
}

func CreateBlockVersionBacklinkUnionBlockVersionBacklink2(blockVersionBacklink2 BlockVersionBacklink2) BlockVersionBacklinkUnion {
	typ := BlockVersionBacklinkUnionTypeBlockVersionBacklink2

	return BlockVersionBacklinkUnion{
		BlockVersionBacklink2: &blockVersionBacklink2,
		Type:                  typ,
	}
}

func (u *BlockVersionBacklinkUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var blockVersionBacklink1 BlockVersionBacklink1 = BlockVersionBacklink1{}
	if err := utils.UnmarshalJSON(data, &blockVersionBacklink1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  BlockVersionBacklinkUnionTypeBlockVersionBacklink1,
			Value: &blockVersionBacklink1,
		})
	}

	var blockVersionBacklink2 BlockVersionBacklink2 = BlockVersionBacklink2{}
	if err := utils.UnmarshalJSON(data, &blockVersionBacklink2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  BlockVersionBacklinkUnionTypeBlockVersionBacklink2,
			Value: &blockVersionBacklink2,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for BlockVersionBacklinkUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for BlockVersionBacklinkUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(BlockVersionBacklinkUnionType)
	switch best.Type {
	case BlockVersionBacklinkUnionTypeBlockVersionBacklink1:
		u.BlockVersionBacklink1 = best.Value.(*BlockVersionBacklink1)
		return nil
	case BlockVersionBacklinkUnionTypeBlockVersionBacklink2:
		u.BlockVersionBacklink2 = best.Value.(*BlockVersionBacklink2)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for BlockVersionBacklinkUnion", string(data))
}

func (u BlockVersionBacklinkUnion) MarshalJSON() ([]byte, error) {
	if u.BlockVersionBacklink1 != nil {
		return utils.MarshalJSON(u.BlockVersionBacklink1, "", true)
	}

	if u.BlockVersionBacklink2 != nil {
		return utils.MarshalJSON(u.BlockVersionBacklink2, "", true)
	}

	return nil, errors.New("could not marshal union type BlockVersionBacklinkUnion: all fields are null")
}
