// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BucketLocalAlias struct {
	AccessKeyID string `json:"accessKeyId"`
	Alias       string `json:"alias"`
}

func (b *BucketLocalAlias) GetAccessKeyID() string {
	if b == nil {
		return ""
	}
	return b.AccessKeyID
}

func (b *BucketLocalAlias) GetAlias() string {
	if b == nil {
		return ""
	}
	return b.Alias
}
