// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CleanupIncompleteUploadsRequest struct {
	BucketID      string `json:"bucketId"`
	OlderThanSecs int64  `json:"olderThanSecs"`
}

func (c *CleanupIncompleteUploadsRequest) GetBucketID() string {
	if c == nil {
		return ""
	}
	return c.BucketID
}

func (c *CleanupIncompleteUploadsRequest) GetOlderThanSecs() int64 {
	if c == nil {
		return 0
	}
	return c.OlderThanSecs
}
