// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CleanupIncompleteUploadsResponse struct {
	UploadsDeleted int64 `json:"uploadsDeleted"`
}

func (c *CleanupIncompleteUploadsResponse) GetUploadsDeleted() int64 {
	if c == nil {
		return 0
	}
	return c.UploadsDeleted
}
