// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ClusterLayoutVersionStatus string

const (
	ClusterLayoutVersionStatusCurrent    ClusterLayoutVersionStatus = "Current"
	ClusterLayoutVersionStatusDraining   ClusterLayoutVersionStatus = "Draining"
	ClusterLayoutVersionStatusHistorical ClusterLayoutVersionStatus = "Historical"
)

func (e ClusterLayoutVersionStatus) ToPointer() *ClusterLayoutVersionStatus {
	return &e
}
func (e *ClusterLayoutVersionStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Current":
		fallthrough
	case "Draining":
		fallthrough
	case "Historical":
		*e = ClusterLayoutVersionStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ClusterLayoutVersionStatus: %v", v)
	}
}
