// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ClusterLayoutVersion struct {
	// Number of nodes with a gateway role in this layout version
	GatewayNodes int64                      `json:"gatewayNodes"`
	Status       ClusterLayoutVersionStatus `json:"status"`
	// Number of nodes with an assigned storage capacity in this layout version
	StorageNodes int64 `json:"storageNodes"`
	// Version number of this layout version
	Version int64 `json:"version"`
}

func (c *ClusterLayoutVersion) GetGatewayNodes() int64 {
	if c == nil {
		return 0
	}
	return c.GatewayNodes
}

func (c *ClusterLayoutVersion) GetStatus() ClusterLayoutVersionStatus {
	if c == nil {
		return ClusterLayoutVersionStatus("")
	}
	return c.Status
}

func (c *ClusterLayoutVersion) GetStorageNodes() int64 {
	if c == nil {
		return 0
	}
	return c.StorageNodes
}

func (c *ClusterLayoutVersion) GetVersion() int64 {
	if c == nil {
		return 0
	}
	return c.Version
}
