// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ClusterLayoutSkipDeadNodesRequest struct {
	// Allow the skip even if a quorum of nodes could not be found for
	// the data among the remaining nodes
	AllowMissingData bool `json:"allowMissingData"`
	// Version number of the layout to assume is currently up-to-date.
	// This will generally be the current layout version.
	Version int64 `json:"version"`
}

func (c *ClusterLayoutSkipDeadNodesRequest) GetAllowMissingData() bool {
	if c == nil {
		return false
	}
	return c.AllowMissingData
}

func (c *ClusterLayoutSkipDeadNodesRequest) GetVersion() int64 {
	if c == nil {
		return 0
	}
	return c.Version
}
