// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ClusterLayoutSkipDeadNodesResponse struct {
	// Nodes for which the ACK update tracker has been updated to `version`
	AckUpdated []string `json:"ackUpdated"`
	// If `allow_missing_data` is set,
	// nodes for which the SYNC update tracker has been updated to `version`
	SyncUpdated []string `json:"syncUpdated"`
}

func (c *ClusterLayoutSkipDeadNodesResponse) GetAckUpdated() []string {
	if c == nil {
		return []string{}
	}
	return c.AckUpdated
}

func (c *ClusterLayoutSkipDeadNodesResponse) GetSyncUpdated() []string {
	if c == nil {
		return []string{}
	}
	return c.SyncUpdated
}
