// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type ConnectNodeResponse struct {
	// An error message if Garage did not manage to connect to this node
	Error optionalnullable.OptionalNullable[string] `json:"error,omitempty"`
	// `true` if Garage managed to connect to this node
	Success bool `json:"success"`
}

func (c *ConnectNodeResponse) GetError() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Error
}

func (c *ConnectNodeResponse) GetSuccess() bool {
	if c == nil {
		return false
	}
	return c.Success
}
