// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/internal/utils"
	"github.com/guilhem/garage-go/optionalnullable"
	"time"
)

type CreateKeyRequest struct {
	Allow optionalnullable.OptionalNullable[KeyPerm] `json:"allow,omitempty"`
	Deny  optionalnullable.OptionalNullable[KeyPerm] `json:"deny,omitempty"`
	// Expiration time and date, formatted according to RFC 3339
	Expiration optionalnullable.OptionalNullable[time.Time] `json:"expiration,omitempty"`
	// Name of the API key
	Name optionalnullable.OptionalNullable[string] `json:"name,omitempty"`
	// Set the access key to never expire
	NeverExpires *bool `json:"neverExpires,omitempty"`
}

func (c CreateKeyRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateKeyRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateKeyRequest) GetAllow() optionalnullable.OptionalNullable[KeyPerm] {
	if c == nil {
		return nil
	}
	return c.Allow
}

func (c *CreateKeyRequest) GetDeny() optionalnullable.OptionalNullable[KeyPerm] {
	if c == nil {
		return nil
	}
	return c.Deny
}

func (c *CreateKeyRequest) GetExpiration() optionalnullable.OptionalNullable[time.Time] {
	if c == nil {
		return nil
	}
	return c.Expiration
}

func (c *CreateKeyRequest) GetName() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateKeyRequest) GetNeverExpires() *bool {
	if c == nil {
		return nil
	}
	return c.NeverExpires
}
