// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/internal/utils"
	"github.com/guilhem/garage-go/optionalnullable"
	"time"
)

type CreateKeyResponse struct {
	AccessKeyID     string                                       `json:"accessKeyId"`
	Buckets         []KeyInfoBucketResponse                      `json:"buckets"`
	Created         optionalnullable.OptionalNullable[time.Time] `json:"created,omitempty"`
	Expiration      optionalnullable.OptionalNullable[time.Time] `json:"expiration,omitempty"`
	Expired         bool                                         `json:"expired"`
	Name            string                                       `json:"name"`
	Permissions     KeyPerm                                      `json:"permissions"`
	SecretAccessKey optionalnullable.OptionalNullable[string]    `json:"secretAccessKey,omitempty"`
}

func (c CreateKeyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateKeyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"accessKeyId", "buckets", "expired", "name", "permissions"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateKeyResponse) GetAccessKeyID() string {
	if c == nil {
		return ""
	}
	return c.AccessKeyID
}

func (c *CreateKeyResponse) GetBuckets() []KeyInfoBucketResponse {
	if c == nil {
		return []KeyInfoBucketResponse{}
	}
	return c.Buckets
}

func (c *CreateKeyResponse) GetCreated() optionalnullable.OptionalNullable[time.Time] {
	if c == nil {
		return nil
	}
	return c.Created
}

func (c *CreateKeyResponse) GetExpiration() optionalnullable.OptionalNullable[time.Time] {
	if c == nil {
		return nil
	}
	return c.Expiration
}

func (c *CreateKeyResponse) GetExpired() bool {
	if c == nil {
		return false
	}
	return c.Expired
}

func (c *CreateKeyResponse) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateKeyResponse) GetPermissions() KeyPerm {
	if c == nil {
		return KeyPerm{}
	}
	return c.Permissions
}

func (c *CreateKeyResponse) GetSecretAccessKey() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.SecretAccessKey
}
