// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/internal/utils"
	"github.com/guilhem/garage-go/optionalnullable"
	"time"
)

type CreateAdminTokenResponse struct {
	// Creation date
	Created optionalnullable.OptionalNullable[time.Time] `json:"created,omitempty"`
	// Expiration time and date, formatted according to RFC 3339
	Expiration optionalnullable.OptionalNullable[time.Time] `json:"expiration,omitempty"`
	// Whether this admin token is expired already
	Expired bool `json:"expired"`
	// Identifier of the admin token (which is also a prefix of the full bearer token)
	ID optionalnullable.OptionalNullable[string] `json:"id,omitempty"`
	// Name of the admin API token
	Name string `json:"name"`
	// Scope of the admin API token, a list of admin endpoint names (such as
	// `GetClusterStatus`, etc), or the special value `*` to allow all
	// admin endpoints
	Scope []string `json:"scope"`
	// The secret bearer token. **CAUTION:** This token will be shown only
	// ONCE, so this value MUST be remembered somewhere, or the token
	// will be unusable.
	SecretToken string `json:"secretToken"`
}

func (c CreateAdminTokenResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAdminTokenResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"expired", "name", "scope", "secretToken"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateAdminTokenResponse) GetCreated() optionalnullable.OptionalNullable[time.Time] {
	if c == nil {
		return nil
	}
	return c.Created
}

func (c *CreateAdminTokenResponse) GetExpiration() optionalnullable.OptionalNullable[time.Time] {
	if c == nil {
		return nil
	}
	return c.Expiration
}

func (c *CreateAdminTokenResponse) GetExpired() bool {
	if c == nil {
		return false
	}
	return c.Expired
}

func (c *CreateAdminTokenResponse) GetID() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CreateAdminTokenResponse) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateAdminTokenResponse) GetScope() []string {
	if c == nil {
		return []string{}
	}
	return c.Scope
}

func (c *CreateAdminTokenResponse) GetSecretToken() string {
	if c == nil {
		return ""
	}
	return c.SecretToken
}
