// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateBucketLocalAlias struct {
	AccessKeyID string            `json:"accessKeyId"`
	Alias       string            `json:"alias"`
	Allow       *APIBucketKeyPerm `json:"allow,omitempty"`
}

func (c *CreateBucketLocalAlias) GetAccessKeyID() string {
	if c == nil {
		return ""
	}
	return c.AccessKeyID
}

func (c *CreateBucketLocalAlias) GetAlias() string {
	if c == nil {
		return ""
	}
	return c.Alias
}

func (c *CreateBucketLocalAlias) GetAllow() *APIBucketKeyPerm {
	if c == nil {
		return nil
	}
	return c.Allow
}
