// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type CreateBucketRequest struct {
	GlobalAlias optionalnullable.OptionalNullable[string]                 `json:"globalAlias,omitempty"`
	LocalAlias  optionalnullable.OptionalNullable[CreateBucketLocalAlias] `json:"localAlias,omitempty"`
}

func (c *CreateBucketRequest) GetGlobalAlias() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.GlobalAlias
}

func (c *CreateBucketRequest) GetLocalAlias() optionalnullable.OptionalNullable[CreateBucketLocalAlias] {
	if c == nil {
		return nil
	}
	return c.LocalAlias
}
