// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FreeSpaceResp struct {
	// Number of bytes available
	Available int64 `json:"available"`
	// Total number of bytes
	Total int64 `json:"total"`
}

func (f *FreeSpaceResp) GetAvailable() int64 {
	if f == nil {
		return 0
	}
	return f.Available
}

func (f *FreeSpaceResp) GetTotal() int64 {
	if f == nil {
		return 0
	}
	return f.Total
}
