// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/internal/utils"
	"github.com/guilhem/garage-go/optionalnullable"
	"time"
)

type GetAdminTokenInfoResponse struct {
	// Creation date
	Created optionalnullable.OptionalNullable[time.Time] `json:"created,omitempty"`
	// Expiration time and date, formatted according to RFC 3339
	Expiration optionalnullable.OptionalNullable[time.Time] `json:"expiration,omitempty"`
	// Whether this admin token is expired already
	Expired bool `json:"expired"`
	// Identifier of the admin token (which is also a prefix of the full bearer token)
	ID optionalnullable.OptionalNullable[string] `json:"id,omitempty"`
	// Name of the admin API token
	Name string `json:"name"`
	// Scope of the admin API token, a list of admin endpoint names (such as
	// `GetClusterStatus`, etc), or the special value `*` to allow all
	// admin endpoints
	Scope []string `json:"scope"`
}

func (g GetAdminTokenInfoResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAdminTokenInfoResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"expired", "name", "scope"}); err != nil {
		return err
	}
	return nil
}

func (g *GetAdminTokenInfoResponse) GetCreated() optionalnullable.OptionalNullable[time.Time] {
	if g == nil {
		return nil
	}
	return g.Created
}

func (g *GetAdminTokenInfoResponse) GetExpiration() optionalnullable.OptionalNullable[time.Time] {
	if g == nil {
		return nil
	}
	return g.Expiration
}

func (g *GetAdminTokenInfoResponse) GetExpired() bool {
	if g == nil {
		return false
	}
	return g.Expired
}

func (g *GetAdminTokenInfoResponse) GetID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GetAdminTokenInfoResponse) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetAdminTokenInfoResponse) GetScope() []string {
	if g == nil {
		return []string{}
	}
	return g.Scope
}
