// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type GetBucketInfoWebsiteResponse struct {
	ErrorDocument optionalnullable.OptionalNullable[string] `json:"errorDocument,omitempty"`
	IndexDocument string                                    `json:"indexDocument"`
}

func (g *GetBucketInfoWebsiteResponse) GetErrorDocument() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.ErrorDocument
}

func (g *GetBucketInfoWebsiteResponse) GetIndexDocument() string {
	if g == nil {
		return ""
	}
	return g.IndexDocument
}
