// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetBucketInfoKey struct {
	AccessKeyID        string           `json:"accessKeyId"`
	BucketLocalAliases []string         `json:"bucketLocalAliases"`
	Name               string           `json:"name"`
	Permissions        APIBucketKeyPerm `json:"permissions"`
}

func (g *GetBucketInfoKey) GetAccessKeyID() string {
	if g == nil {
		return ""
	}
	return g.AccessKeyID
}

func (g *GetBucketInfoKey) GetBucketLocalAliases() []string {
	if g == nil {
		return []string{}
	}
	return g.BucketLocalAliases
}

func (g *GetBucketInfoKey) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetBucketInfoKey) GetPermissions() APIBucketKeyPerm {
	if g == nil {
		return APIBucketKeyPerm{}
	}
	return g.Permissions
}
