// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetClusterStatisticsResponse struct {
	Freeform string `json:"freeform"`
}

func (g *GetClusterStatisticsResponse) GetFreeform() string {
	if g == nil {
		return ""
	}
	return g.Freeform
}
