// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetClusterHealthResponse struct {
	// the nubmer of nodes this Garage node currently has an open connection to
	ConnectedNodes int64 `json:"connectedNodes"`
	// the number of nodes this Garage node has had a TCP connection to since the daemon started
	KnownNodes int64 `json:"knownNodes"`
	// the total number of partitions of the data (currently always 256)
	Partitions int64 `json:"partitions"`
	// the number of partitions for which we are connected to all storage nodes responsible of storing it
	PartitionsAllOk int64 `json:"partitionsAllOk"`
	// the number of partitions for which a quorum of write nodes is available
	PartitionsQuorum int64 `json:"partitionsQuorum"`
	// One of `healthy`, `degraded` or `unavailable`:
	// - `healthy`: Garage node is connected to all storage nodes
	// - `degraded`: Garage node is not connected to all storage nodes, but a quorum of write nodes is available for all partitions
	// - `unavailable`: a quorum of write nodes is not available for some partitions
	Status string `json:"status"`
	// the number of storage nodes currently registered in the cluster layout
	StorageNodes int64 `json:"storageNodes"`
	// the number of storage nodes to which a connection is currently open
	StorageNodesUp int64 `json:"storageNodesUp"`
}

func (g *GetClusterHealthResponse) GetConnectedNodes() int64 {
	if g == nil {
		return 0
	}
	return g.ConnectedNodes
}

func (g *GetClusterHealthResponse) GetKnownNodes() int64 {
	if g == nil {
		return 0
	}
	return g.KnownNodes
}

func (g *GetClusterHealthResponse) GetPartitions() int64 {
	if g == nil {
		return 0
	}
	return g.Partitions
}

func (g *GetClusterHealthResponse) GetPartitionsAllOk() int64 {
	if g == nil {
		return 0
	}
	return g.PartitionsAllOk
}

func (g *GetClusterHealthResponse) GetPartitionsQuorum() int64 {
	if g == nil {
		return 0
	}
	return g.PartitionsQuorum
}

func (g *GetClusterHealthResponse) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetClusterHealthResponse) GetStorageNodes() int64 {
	if g == nil {
		return 0
	}
	return g.StorageNodes
}

func (g *GetClusterHealthResponse) GetStorageNodesUp() int64 {
	if g == nil {
		return 0
	}
	return g.StorageNodesUp
}
