// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetClusterStatusResponse struct {
	// Current version number of the cluster layout
	LayoutVersion int64 `json:"layoutVersion"`
	// List of nodes that are either currently connected, part of the
	// current cluster layout, or part of an older cluster layout that
	// is still active in the cluster (being drained).
	Nodes []NodeResp `json:"nodes"`
}

func (g *GetClusterStatusResponse) GetLayoutVersion() int64 {
	if g == nil {
		return 0
	}
	return g.LayoutVersion
}

func (g *GetClusterStatusResponse) GetNodes() []NodeResp {
	if g == nil {
		return []NodeResp{}
	}
	return g.Nodes
}
