// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type GetClusterLayoutHistoryResponse struct {
	// The current version number of the cluster layout
	CurrentVersion int64 `json:"currentVersion"`
	// All nodes in the cluster are aware of layout versions up to
	// this version number (at least)
	MinAck int64 `json:"minAck"`
	// Detailed update trackers for nodes (see
	// `https://garagehq.deuxfleurs.fr/blog/2023-12-preserving-read-after-write-consistency/`)
	UpdateTrackers optionalnullable.OptionalNullable[map[string]NodeUpdateTrackers] `json:"updateTrackers,omitempty"`
	// Layout version history
	Versions []ClusterLayoutVersion `json:"versions"`
}

func (g *GetClusterLayoutHistoryResponse) GetCurrentVersion() int64 {
	if g == nil {
		return 0
	}
	return g.CurrentVersion
}

func (g *GetClusterLayoutHistoryResponse) GetMinAck() int64 {
	if g == nil {
		return 0
	}
	return g.MinAck
}

func (g *GetClusterLayoutHistoryResponse) GetUpdateTrackers() optionalnullable.OptionalNullable[map[string]NodeUpdateTrackers] {
	if g == nil {
		return nil
	}
	return g.UpdateTrackers
}

func (g *GetClusterLayoutHistoryResponse) GetVersions() []ClusterLayoutVersion {
	if g == nil {
		return []ClusterLayoutVersion{}
	}
	return g.Versions
}
