// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/internal/utils"
	"github.com/guilhem/garage-go/optionalnullable"
)

type GetClusterLayoutResponse struct {
	Parameters LayoutParameters `json:"parameters"`
	// The size, in bytes, of one Garage partition (= a shard)
	PartitionSize int64 `json:"partitionSize"`
	// List of nodes that currently have a role in the cluster layout
	Roles            []LayoutNodeRole                                    `json:"roles"`
	StagedParameters optionalnullable.OptionalNullable[LayoutParameters] `json:"stagedParameters,omitempty"`
	// List of nodes that will have a new role or whose role will be
	// removed in the next version of the cluster layout
	StagedRoleChanges []NodeRoleChangeUnion `json:"stagedRoleChanges"`
	// The current version number of the cluster layout
	Version int64 `json:"version"`
}

func (g GetClusterLayoutResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetClusterLayoutResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"parameters", "partitionSize", "roles", "stagedRoleChanges", "version"}); err != nil {
		return err
	}
	return nil
}

func (g *GetClusterLayoutResponse) GetParameters() LayoutParameters {
	if g == nil {
		return LayoutParameters{}
	}
	return g.Parameters
}

func (g *GetClusterLayoutResponse) GetPartitionSize() int64 {
	if g == nil {
		return 0
	}
	return g.PartitionSize
}

func (g *GetClusterLayoutResponse) GetRoles() []LayoutNodeRole {
	if g == nil {
		return []LayoutNodeRole{}
	}
	return g.Roles
}

func (g *GetClusterLayoutResponse) GetStagedParameters() optionalnullable.OptionalNullable[LayoutParameters] {
	if g == nil {
		return nil
	}
	return g.StagedParameters
}

func (g *GetClusterLayoutResponse) GetStagedRoleChanges() []NodeRoleChangeUnion {
	if g == nil {
		return []NodeRoleChangeUnion{}
	}
	return g.StagedRoleChanges
}

func (g *GetClusterLayoutResponse) GetVersion() int64 {
	if g == nil {
		return 0
	}
	return g.Version
}
