// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type ImportKeyRequest struct {
	AccessKeyID     string                                    `json:"accessKeyId"`
	Name            optionalnullable.OptionalNullable[string] `json:"name,omitempty"`
	SecretAccessKey string                                    `json:"secretAccessKey"`
}

func (i *ImportKeyRequest) GetAccessKeyID() string {
	if i == nil {
		return ""
	}
	return i.AccessKeyID
}

func (i *ImportKeyRequest) GetName() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.Name
}

func (i *ImportKeyRequest) GetSecretAccessKey() string {
	if i == nil {
		return ""
	}
	return i.SecretAccessKey
}
