// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InspectObjectBlock struct {
	// Hash (blake2 sum) of the block's data
	Hash string `json:"hash"`
	// Offset of this block within the part
	Offset int64 `json:"offset"`
	// Part number of the part containing this block, for multipart uploads
	PartNumber int64 `json:"partNumber"`
	// Length of the blocks's data
	Size int64 `json:"size"`
}

func (i *InspectObjectBlock) GetHash() string {
	if i == nil {
		return ""
	}
	return i.Hash
}

func (i *InspectObjectBlock) GetOffset() int64 {
	if i == nil {
		return 0
	}
	return i.Offset
}

func (i *InspectObjectBlock) GetPartNumber() int64 {
	if i == nil {
		return 0
	}
	return i.PartNumber
}

func (i *InspectObjectBlock) GetSize() int64 {
	if i == nil {
		return 0
	}
	return i.Size
}
