// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/internal/utils"
	"github.com/guilhem/garage-go/optionalnullable"
	"time"
)

type InspectObjectVersion struct {
	// Whether this is an aborted upload
	Aborted bool `json:"aborted"`
	// List of data blocks for this object version
	Blocks []InspectObjectBlock `json:"blocks,omitempty"`
	// Whether this version is a delete marker (a tombstone indicating that a previous version of
	// the object has been deleted)
	DeleteMarker bool `json:"deleteMarker"`
	// Whether this object version was created with SSE-C encryption
	Encrypted bool `json:"encrypted"`
	// Etag of this object version
	Etag optionalnullable.OptionalNullable[string] `json:"etag,omitempty"`
	// Metadata (HTTP headers) associated with this object version
	Headers [][]string `json:"headers,omitempty"`
	// Whether the object's data is stored inline (for small objects)
	Inline bool `json:"inline"`
	// Size of the object, in bytes
	Size optionalnullable.OptionalNullable[int64] `json:"size,omitempty"`
	// Creation timestamp of this object version
	Timestamp time.Time `json:"timestamp"`
	// Whether this object version is still uploading
	Uploading bool `json:"uploading"`
	// Version ID
	UUID string `json:"uuid"`
}

func (i InspectObjectVersion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InspectObjectVersion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"aborted", "deleteMarker", "encrypted", "inline", "timestamp", "uploading", "uuid"}); err != nil {
		return err
	}
	return nil
}

func (i *InspectObjectVersion) GetAborted() bool {
	if i == nil {
		return false
	}
	return i.Aborted
}

func (i *InspectObjectVersion) GetBlocks() []InspectObjectBlock {
	if i == nil {
		return nil
	}
	return i.Blocks
}

func (i *InspectObjectVersion) GetDeleteMarker() bool {
	if i == nil {
		return false
	}
	return i.DeleteMarker
}

func (i *InspectObjectVersion) GetEncrypted() bool {
	if i == nil {
		return false
	}
	return i.Encrypted
}

func (i *InspectObjectVersion) GetEtag() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.Etag
}

func (i *InspectObjectVersion) GetHeaders() [][]string {
	if i == nil {
		return nil
	}
	return i.Headers
}

func (i *InspectObjectVersion) GetInline() bool {
	if i == nil {
		return false
	}
	return i.Inline
}

func (i *InspectObjectVersion) GetSize() optionalnullable.OptionalNullable[int64] {
	if i == nil {
		return nil
	}
	return i.Size
}

func (i *InspectObjectVersion) GetTimestamp() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.Timestamp
}

func (i *InspectObjectVersion) GetUploading() bool {
	if i == nil {
		return false
	}
	return i.Uploading
}

func (i *InspectObjectVersion) GetUUID() string {
	if i == nil {
		return ""
	}
	return i.UUID
}
