// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InspectObjectResponse struct {
	// ID of the bucket containing the inspected object
	BucketID string `json:"bucketId"`
	// Key of the inspected object
	Key string `json:"key"`
	// List of versions currently stored for this object
	Versions []InspectObjectVersion `json:"versions"`
}

func (i *InspectObjectResponse) GetBucketID() string {
	if i == nil {
		return ""
	}
	return i.BucketID
}

func (i *InspectObjectResponse) GetKey() string {
	if i == nil {
		return ""
	}
	return i.Key
}

func (i *InspectObjectResponse) GetVersions() []InspectObjectVersion {
	if i == nil {
		return []InspectObjectVersion{}
	}
	return i.Versions
}
