// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type KeyInfoBucketResponse struct {
	GlobalAliases []string         `json:"globalAliases"`
	ID            string           `json:"id"`
	LocalAliases  []string         `json:"localAliases"`
	Permissions   APIBucketKeyPerm `json:"permissions"`
}

func (k *KeyInfoBucketResponse) GetGlobalAliases() []string {
	if k == nil {
		return []string{}
	}
	return k.GlobalAliases
}

func (k *KeyInfoBucketResponse) GetID() string {
	if k == nil {
		return ""
	}
	return k.ID
}

func (k *KeyInfoBucketResponse) GetLocalAliases() []string {
	if k == nil {
		return []string{}
	}
	return k.LocalAliases
}

func (k *KeyInfoBucketResponse) GetPermissions() APIBucketKeyPerm {
	if k == nil {
		return APIBucketKeyPerm{}
	}
	return k.Permissions
}
