// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type KeyPerm struct {
	CreateBucket *bool `json:"createBucket,omitempty"`
}

func (k *KeyPerm) GetCreateBucket() *bool {
	if k == nil {
		return nil
	}
	return k.CreateBucket
}
