// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/internal/utils"
)

type LayoutParameters struct {
	ZoneRedundancy ZoneRedundancyUnion `json:"zoneRedundancy"`
}

func (l LayoutParameters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LayoutParameters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"zoneRedundancy"}); err != nil {
		return err
	}
	return nil
}

func (l *LayoutParameters) GetZoneRedundancy() ZoneRedundancyUnion {
	if l == nil {
		return ZoneRedundancyUnion{}
	}
	return l.ZoneRedundancy
}
