// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/internal/utils"
	"github.com/guilhem/garage-go/optionalnullable"
)

type LayoutNodeRole struct {
	// Capacity (in bytes) assigned by the cluster administrator,
	// absent for gateway nodes
	Capacity optionalnullable.OptionalNullable[int64] `json:"capacity,omitempty"`
	// Identifier of the node
	ID string `json:"id"`
	// Number of partitions stored on this node
	// (a result of the layout computation)
	StoredPartitions optionalnullable.OptionalNullable[int64] `json:"storedPartitions,omitempty"`
	// List of tags assigned by the cluster administrator
	Tags []string `json:"tags"`
	// Capacity (in bytes) that is actually usable on this node in the current
	// layout, which is equal to `stored_partitions` × `partition_size`
	UsableCapacity optionalnullable.OptionalNullable[int64] `json:"usableCapacity,omitempty"`
	// Zone name assigned by the cluster administrator
	Zone string `json:"zone"`
}

func (l LayoutNodeRole) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LayoutNodeRole) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"id", "tags", "zone"}); err != nil {
		return err
	}
	return nil
}

func (l *LayoutNodeRole) GetCapacity() optionalnullable.OptionalNullable[int64] {
	if l == nil {
		return nil
	}
	return l.Capacity
}

func (l *LayoutNodeRole) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *LayoutNodeRole) GetStoredPartitions() optionalnullable.OptionalNullable[int64] {
	if l == nil {
		return nil
	}
	return l.StoredPartitions
}

func (l *LayoutNodeRole) GetTags() []string {
	if l == nil {
		return []string{}
	}
	return l.Tags
}

func (l *LayoutNodeRole) GetUsableCapacity() optionalnullable.OptionalNullable[int64] {
	if l == nil {
		return nil
	}
	return l.UsableCapacity
}

func (l *LayoutNodeRole) GetZone() string {
	if l == nil {
		return ""
	}
	return l.Zone
}
