// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/internal/utils"
	"time"
)

type ListBucketsResponseItem struct {
	Created       time.Time          `json:"created"`
	GlobalAliases []string           `json:"globalAliases"`
	ID            string             `json:"id"`
	LocalAliases  []BucketLocalAlias `json:"localAliases"`
}

func (l ListBucketsResponseItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListBucketsResponseItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"created", "globalAliases", "id", "localAliases"}); err != nil {
		return err
	}
	return nil
}

func (l *ListBucketsResponseItem) GetCreated() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Created
}

func (l *ListBucketsResponseItem) GetGlobalAliases() []string {
	if l == nil {
		return []string{}
	}
	return l.GlobalAliases
}

func (l *ListBucketsResponseItem) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListBucketsResponseItem) GetLocalAliases() []BucketLocalAlias {
	if l == nil {
		return []BucketLocalAlias{}
	}
	return l.LocalAliases
}
