// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/internal/utils"
	"github.com/guilhem/garage-go/optionalnullable"
	"time"
)

type ListKeysResponseItem struct {
	Created    optionalnullable.OptionalNullable[time.Time] `json:"created,omitempty"`
	Expiration optionalnullable.OptionalNullable[time.Time] `json:"expiration,omitempty"`
	Expired    bool                                         `json:"expired"`
	ID         string                                       `json:"id"`
	Name       string                                       `json:"name"`
}

func (l ListKeysResponseItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListKeysResponseItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"expired", "id", "name"}); err != nil {
		return err
	}
	return nil
}

func (l *ListKeysResponseItem) GetCreated() optionalnullable.OptionalNullable[time.Time] {
	if l == nil {
		return nil
	}
	return l.Created
}

func (l *ListKeysResponseItem) GetExpiration() optionalnullable.OptionalNullable[time.Time] {
	if l == nil {
		return nil
	}
	return l.Expiration
}

func (l *ListKeysResponseItem) GetExpired() bool {
	if l == nil {
		return false
	}
	return l.Expired
}

func (l *ListKeysResponseItem) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListKeysResponseItem) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}
