// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/guilhem/garage-go/internal/utils"
)

type LocalRetryBlockResyncRequest2 struct {
	BlockHashes []string `json:"blockHashes"`
}

func (l LocalRetryBlockResyncRequest2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LocalRetryBlockResyncRequest2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"blockHashes"}); err != nil {
		return err
	}
	return nil
}

func (l *LocalRetryBlockResyncRequest2) GetBlockHashes() []string {
	if l == nil {
		return []string{}
	}
	return l.BlockHashes
}

type LocalRetryBlockResyncRequest1 struct {
	All bool `json:"all"`
}

func (l LocalRetryBlockResyncRequest1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LocalRetryBlockResyncRequest1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"all"}); err != nil {
		return err
	}
	return nil
}

func (l *LocalRetryBlockResyncRequest1) GetAll() bool {
	if l == nil {
		return false
	}
	return l.All
}

type LocalRetryBlockResyncRequestUnionType string

const (
	LocalRetryBlockResyncRequestUnionTypeLocalRetryBlockResyncRequest1 LocalRetryBlockResyncRequestUnionType = "LocalRetryBlockResyncRequest_1"
	LocalRetryBlockResyncRequestUnionTypeLocalRetryBlockResyncRequest2 LocalRetryBlockResyncRequestUnionType = "LocalRetryBlockResyncRequest_2"
)

type LocalRetryBlockResyncRequestUnion struct {
	LocalRetryBlockResyncRequest1 *LocalRetryBlockResyncRequest1 `queryParam:"inline,name=LocalRetryBlockResyncRequest"`
	LocalRetryBlockResyncRequest2 *LocalRetryBlockResyncRequest2 `queryParam:"inline,name=LocalRetryBlockResyncRequest"`

	Type LocalRetryBlockResyncRequestUnionType
}

func CreateLocalRetryBlockResyncRequestUnionLocalRetryBlockResyncRequest1(localRetryBlockResyncRequest1 LocalRetryBlockResyncRequest1) LocalRetryBlockResyncRequestUnion {
	typ := LocalRetryBlockResyncRequestUnionTypeLocalRetryBlockResyncRequest1

	return LocalRetryBlockResyncRequestUnion{
		LocalRetryBlockResyncRequest1: &localRetryBlockResyncRequest1,
		Type:                          typ,
	}
}

func CreateLocalRetryBlockResyncRequestUnionLocalRetryBlockResyncRequest2(localRetryBlockResyncRequest2 LocalRetryBlockResyncRequest2) LocalRetryBlockResyncRequestUnion {
	typ := LocalRetryBlockResyncRequestUnionTypeLocalRetryBlockResyncRequest2

	return LocalRetryBlockResyncRequestUnion{
		LocalRetryBlockResyncRequest2: &localRetryBlockResyncRequest2,
		Type:                          typ,
	}
}

func (u *LocalRetryBlockResyncRequestUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var localRetryBlockResyncRequest1 LocalRetryBlockResyncRequest1 = LocalRetryBlockResyncRequest1{}
	if err := utils.UnmarshalJSON(data, &localRetryBlockResyncRequest1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  LocalRetryBlockResyncRequestUnionTypeLocalRetryBlockResyncRequest1,
			Value: &localRetryBlockResyncRequest1,
		})
	}

	var localRetryBlockResyncRequest2 LocalRetryBlockResyncRequest2 = LocalRetryBlockResyncRequest2{}
	if err := utils.UnmarshalJSON(data, &localRetryBlockResyncRequest2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  LocalRetryBlockResyncRequestUnionTypeLocalRetryBlockResyncRequest2,
			Value: &localRetryBlockResyncRequest2,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for LocalRetryBlockResyncRequestUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for LocalRetryBlockResyncRequestUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(LocalRetryBlockResyncRequestUnionType)
	switch best.Type {
	case LocalRetryBlockResyncRequestUnionTypeLocalRetryBlockResyncRequest1:
		u.LocalRetryBlockResyncRequest1 = best.Value.(*LocalRetryBlockResyncRequest1)
		return nil
	case LocalRetryBlockResyncRequestUnionTypeLocalRetryBlockResyncRequest2:
		u.LocalRetryBlockResyncRequest2 = best.Value.(*LocalRetryBlockResyncRequest2)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for LocalRetryBlockResyncRequestUnion", string(data))
}

func (u LocalRetryBlockResyncRequestUnion) MarshalJSON() ([]byte, error) {
	if u.LocalRetryBlockResyncRequest1 != nil {
		return utils.MarshalJSON(u.LocalRetryBlockResyncRequest1, "", true)
	}

	if u.LocalRetryBlockResyncRequest2 != nil {
		return utils.MarshalJSON(u.LocalRetryBlockResyncRequest2, "", true)
	}

	return nil, errors.New("could not marshal union type LocalRetryBlockResyncRequestUnion: all fields are null")
}
