// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LocalGetWorkerInfoRequest struct {
	ID int64 `json:"id"`
}

func (l *LocalGetWorkerInfoRequest) GetID() int64 {
	if l == nil {
		return 0
	}
	return l.ID
}
