// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LocalSetWorkerVariableRequest struct {
	Value    string `json:"value"`
	Variable string `json:"variable"`
}

func (l *LocalSetWorkerVariableRequest) GetValue() string {
	if l == nil {
		return ""
	}
	return l.Value
}

func (l *LocalSetWorkerVariableRequest) GetVariable() string {
	if l == nil {
		return ""
	}
	return l.Variable
}
