// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LocalLaunchRepairOperationRequest struct {
	RepairType RepairTypeUnion `json:"repairType"`
}

func (l *LocalLaunchRepairOperationRequest) GetRepairType() RepairTypeUnion {
	if l == nil {
		return RepairTypeUnion{}
	}
	return l.RepairType
}
