// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type LocalGetWorkerVariableRequest struct {
	Variable optionalnullable.OptionalNullable[string] `json:"variable,omitempty"`
}

func (l *LocalGetWorkerVariableRequest) GetVariable() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.Variable
}
