// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LocalListWorkersRequest struct {
	BusyOnly  *bool `json:"busyOnly,omitempty"`
	ErrorOnly *bool `json:"errorOnly,omitempty"`
}

func (l *LocalListWorkersRequest) GetBusyOnly() *bool {
	if l == nil {
		return nil
	}
	return l.BusyOnly
}

func (l *LocalListWorkersRequest) GetErrorOnly() *bool {
	if l == nil {
		return nil
	}
	return l.ErrorOnly
}
