// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LocalGetBlockInfoRequest struct {
	BlockHash string `json:"blockHash"`
}

func (l *LocalGetBlockInfoRequest) GetBlockHash() string {
	if l == nil {
		return ""
	}
	return l.BlockHash
}
