// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MultiResponseLocalSetWorkerVariableResponseSuccess struct {
	Value    string `json:"value"`
	Variable string `json:"variable"`
}

func (m *MultiResponseLocalSetWorkerVariableResponseSuccess) GetValue() string {
	if m == nil {
		return ""
	}
	return m.Value
}

func (m *MultiResponseLocalSetWorkerVariableResponseSuccess) GetVariable() string {
	if m == nil {
		return ""
	}
	return m.Variable
}

type MultiResponseLocalSetWorkerVariableResponse struct {
	// Map of node id to error message, for nodes that were unable to complete the API
	// call
	Error map[string]string `json:"error"`
	// Map of node id to response returned by this node, for nodes that were able to
	// successfully complete the API call
	Success map[string]MultiResponseLocalSetWorkerVariableResponseSuccess `json:"success"`
}

func (m *MultiResponseLocalSetWorkerVariableResponse) GetError() map[string]string {
	if m == nil {
		return map[string]string{}
	}
	return m.Error
}

func (m *MultiResponseLocalSetWorkerVariableResponse) GetSuccess() map[string]MultiResponseLocalSetWorkerVariableResponseSuccess {
	if m == nil {
		return map[string]MultiResponseLocalSetWorkerVariableResponseSuccess{}
	}
	return m.Success
}
