// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type MultiResponseLocalGetNodeInfoResponseSuccess struct {
	DbEngine       string                                      `json:"dbEngine"`
	GarageFeatures optionalnullable.OptionalNullable[[]string] `json:"garageFeatures,omitempty"`
	GarageVersion  string                                      `json:"garageVersion"`
	NodeID         string                                      `json:"nodeId"`
	RustVersion    string                                      `json:"rustVersion"`
}

func (m *MultiResponseLocalGetNodeInfoResponseSuccess) GetDbEngine() string {
	if m == nil {
		return ""
	}
	return m.DbEngine
}

func (m *MultiResponseLocalGetNodeInfoResponseSuccess) GetGarageFeatures() optionalnullable.OptionalNullable[[]string] {
	if m == nil {
		return nil
	}
	return m.GarageFeatures
}

func (m *MultiResponseLocalGetNodeInfoResponseSuccess) GetGarageVersion() string {
	if m == nil {
		return ""
	}
	return m.GarageVersion
}

func (m *MultiResponseLocalGetNodeInfoResponseSuccess) GetNodeID() string {
	if m == nil {
		return ""
	}
	return m.NodeID
}

func (m *MultiResponseLocalGetNodeInfoResponseSuccess) GetRustVersion() string {
	if m == nil {
		return ""
	}
	return m.RustVersion
}

type MultiResponseLocalGetNodeInfoResponse struct {
	// Map of node id to error message, for nodes that were unable to complete the API
	// call
	Error map[string]string `json:"error"`
	// Map of node id to response returned by this node, for nodes that were able to
	// successfully complete the API call
	Success map[string]MultiResponseLocalGetNodeInfoResponseSuccess `json:"success"`
}

func (m *MultiResponseLocalGetNodeInfoResponse) GetError() map[string]string {
	if m == nil {
		return map[string]string{}
	}
	return m.Error
}

func (m *MultiResponseLocalGetNodeInfoResponse) GetSuccess() map[string]MultiResponseLocalGetNodeInfoResponseSuccess {
	if m == nil {
		return map[string]MultiResponseLocalGetNodeInfoResponseSuccess{}
	}
	return m.Success
}
