// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MultiResponseLocalRetryBlockResyncResponseSuccess struct {
	Count int64 `json:"count"`
}

func (m *MultiResponseLocalRetryBlockResyncResponseSuccess) GetCount() int64 {
	if m == nil {
		return 0
	}
	return m.Count
}

type MultiResponseLocalRetryBlockResyncResponse struct {
	// Map of node id to error message, for nodes that were unable to complete the API
	// call
	Error map[string]string `json:"error"`
	// Map of node id to response returned by this node, for nodes that were able to
	// successfully complete the API call
	Success map[string]MultiResponseLocalRetryBlockResyncResponseSuccess `json:"success"`
}

func (m *MultiResponseLocalRetryBlockResyncResponse) GetError() map[string]string {
	if m == nil {
		return map[string]string{}
	}
	return m.Error
}

func (m *MultiResponseLocalRetryBlockResyncResponse) GetSuccess() map[string]MultiResponseLocalRetryBlockResyncResponseSuccess {
	if m == nil {
		return map[string]MultiResponseLocalRetryBlockResyncResponseSuccess{}
	}
	return m.Success
}
