// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MultiResponseLocalPurgeBlocksResponseSuccess struct {
	BlockRefsPurged int64 `json:"blockRefsPurged"`
	BlocksPurged    int64 `json:"blocksPurged"`
	ObjectsDeleted  int64 `json:"objectsDeleted"`
	UploadsDeleted  int64 `json:"uploadsDeleted"`
	VersionsDeleted int64 `json:"versionsDeleted"`
}

func (m *MultiResponseLocalPurgeBlocksResponseSuccess) GetBlockRefsPurged() int64 {
	if m == nil {
		return 0
	}
	return m.BlockRefsPurged
}

func (m *MultiResponseLocalPurgeBlocksResponseSuccess) GetBlocksPurged() int64 {
	if m == nil {
		return 0
	}
	return m.BlocksPurged
}

func (m *MultiResponseLocalPurgeBlocksResponseSuccess) GetObjectsDeleted() int64 {
	if m == nil {
		return 0
	}
	return m.ObjectsDeleted
}

func (m *MultiResponseLocalPurgeBlocksResponseSuccess) GetUploadsDeleted() int64 {
	if m == nil {
		return 0
	}
	return m.UploadsDeleted
}

func (m *MultiResponseLocalPurgeBlocksResponseSuccess) GetVersionsDeleted() int64 {
	if m == nil {
		return 0
	}
	return m.VersionsDeleted
}

type MultiResponseLocalPurgeBlocksResponse struct {
	// Map of node id to error message, for nodes that were unable to complete the API
	// call
	Error map[string]string `json:"error"`
	// Map of node id to response returned by this node, for nodes that were able to
	// successfully complete the API call
	Success map[string]MultiResponseLocalPurgeBlocksResponseSuccess `json:"success"`
}

func (m *MultiResponseLocalPurgeBlocksResponse) GetError() map[string]string {
	if m == nil {
		return map[string]string{}
	}
	return m.Error
}

func (m *MultiResponseLocalPurgeBlocksResponse) GetSuccess() map[string]MultiResponseLocalPurgeBlocksResponseSuccess {
	if m == nil {
		return map[string]MultiResponseLocalPurgeBlocksResponseSuccess{}
	}
	return m.Success
}
