// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MultiResponseLocalGetBlockInfoResponseSuccess struct {
	BlockHash string         `json:"blockHash"`
	Refcount  int64          `json:"refcount"`
	Versions  []BlockVersion `json:"versions"`
}

func (m *MultiResponseLocalGetBlockInfoResponseSuccess) GetBlockHash() string {
	if m == nil {
		return ""
	}
	return m.BlockHash
}

func (m *MultiResponseLocalGetBlockInfoResponseSuccess) GetRefcount() int64 {
	if m == nil {
		return 0
	}
	return m.Refcount
}

func (m *MultiResponseLocalGetBlockInfoResponseSuccess) GetVersions() []BlockVersion {
	if m == nil {
		return []BlockVersion{}
	}
	return m.Versions
}

type MultiResponseLocalGetBlockInfoResponse struct {
	// Map of node id to error message, for nodes that were unable to complete the API
	// call
	Error map[string]string `json:"error"`
	// Map of node id to response returned by this node, for nodes that were able to
	// successfully complete the API call
	Success map[string]MultiResponseLocalGetBlockInfoResponseSuccess `json:"success"`
}

func (m *MultiResponseLocalGetBlockInfoResponse) GetError() map[string]string {
	if m == nil {
		return map[string]string{}
	}
	return m.Error
}

func (m *MultiResponseLocalGetBlockInfoResponse) GetSuccess() map[string]MultiResponseLocalGetBlockInfoResponseSuccess {
	if m == nil {
		return map[string]MultiResponseLocalGetBlockInfoResponseSuccess{}
	}
	return m.Success
}
