// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MultiResponseLocalCreateMetadataSnapshotResponse struct {
	// Map of node id to error message, for nodes that were unable to complete the API
	// call
	Error map[string]string `json:"error"`
	// Map of node id to response returned by this node, for nodes that were able to
	// successfully complete the API call
	Success map[string]any `json:"success"`
}

func (m *MultiResponseLocalCreateMetadataSnapshotResponse) GetError() map[string]string {
	if m == nil {
		return map[string]string{}
	}
	return m.Error
}

func (m *MultiResponseLocalCreateMetadataSnapshotResponse) GetSuccess() map[string]any {
	if m == nil {
		return map[string]any{}
	}
	return m.Success
}
