// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MultiResponseLocalGetNodeStatisticsResponseSuccess struct {
	Freeform string `json:"freeform"`
}

func (m *MultiResponseLocalGetNodeStatisticsResponseSuccess) GetFreeform() string {
	if m == nil {
		return ""
	}
	return m.Freeform
}

type MultiResponseLocalGetNodeStatisticsResponse struct {
	// Map of node id to error message, for nodes that were unable to complete the API
	// call
	Error map[string]string `json:"error"`
	// Map of node id to response returned by this node, for nodes that were able to
	// successfully complete the API call
	Success map[string]MultiResponseLocalGetNodeStatisticsResponseSuccess `json:"success"`
}

func (m *MultiResponseLocalGetNodeStatisticsResponse) GetError() map[string]string {
	if m == nil {
		return map[string]string{}
	}
	return m.Error
}

func (m *MultiResponseLocalGetNodeStatisticsResponse) GetSuccess() map[string]MultiResponseLocalGetNodeStatisticsResponseSuccess {
	if m == nil {
		return map[string]MultiResponseLocalGetNodeStatisticsResponseSuccess{}
	}
	return m.Success
}
