// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NodeUpdateTrackers struct {
	Ack     int64 `json:"ack"`
	Sync    int64 `json:"sync"`
	SyncAck int64 `json:"syncAck"`
}

func (n *NodeUpdateTrackers) GetAck() int64 {
	if n == nil {
		return 0
	}
	return n.Ack
}

func (n *NodeUpdateTrackers) GetSync() int64 {
	if n == nil {
		return 0
	}
	return n.Sync
}

func (n *NodeUpdateTrackers) GetSyncAck() int64 {
	if n == nil {
		return 0
	}
	return n.SyncAck
}
