// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type NodeAssignedRole struct {
	// Capacity (in bytes) assigned by the cluster administrator,
	// absent for gateway nodes
	Capacity optionalnullable.OptionalNullable[int64] `json:"capacity,omitempty"`
	// List of tags assigned by the cluster administrator
	Tags []string `json:"tags"`
	// Zone name assigned by the cluster administrator
	Zone string `json:"zone"`
}

func (n *NodeAssignedRole) GetCapacity() optionalnullable.OptionalNullable[int64] {
	if n == nil {
		return nil
	}
	return n.Capacity
}

func (n *NodeAssignedRole) GetTags() []string {
	if n == nil {
		return []string{}
	}
	return n.Tags
}

func (n *NodeAssignedRole) GetZone() string {
	if n == nil {
		return ""
	}
	return n.Zone
}
