// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/guilhem/garage-go/internal/utils"
	"github.com/guilhem/garage-go/optionalnullable"
)

type NodeRoleChangeNodeAssignedRole struct {
	// Capacity (in bytes) assigned by the cluster administrator,
	// absent for gateway nodes
	Capacity optionalnullable.OptionalNullable[int64] `json:"capacity,omitempty"`
	// List of tags assigned by the cluster administrator
	Tags []string `json:"tags"`
	// Zone name assigned by the cluster administrator
	Zone string `json:"zone"`
	// ID of the node for which this change applies
	ID string `json:"id"`
}

func (n NodeRoleChangeNodeAssignedRole) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NodeRoleChangeNodeAssignedRole) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, []string{"tags", "zone", "id"}); err != nil {
		return err
	}
	return nil
}

func (n *NodeRoleChangeNodeAssignedRole) GetCapacity() optionalnullable.OptionalNullable[int64] {
	if n == nil {
		return nil
	}
	return n.Capacity
}

func (n *NodeRoleChangeNodeAssignedRole) GetTags() []string {
	if n == nil {
		return []string{}
	}
	return n.Tags
}

func (n *NodeRoleChangeNodeAssignedRole) GetZone() string {
	if n == nil {
		return ""
	}
	return n.Zone
}

func (n *NodeRoleChangeNodeAssignedRole) GetID() string {
	if n == nil {
		return ""
	}
	return n.ID
}

type NodeRoleChange struct {
	// Set `remove` to `true` to remove the node from the layout
	Remove bool `json:"remove"`
	// ID of the node for which this change applies
	ID string `json:"id"`
}

func (n NodeRoleChange) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NodeRoleChange) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, []string{"remove", "id"}); err != nil {
		return err
	}
	return nil
}

func (n *NodeRoleChange) GetRemove() bool {
	if n == nil {
		return false
	}
	return n.Remove
}

func (n *NodeRoleChange) GetID() string {
	if n == nil {
		return ""
	}
	return n.ID
}

type NodeRoleChangeUnionType string

const (
	NodeRoleChangeUnionTypeNodeRoleChange                 NodeRoleChangeUnionType = "NodeRoleChange"
	NodeRoleChangeUnionTypeNodeRoleChangeNodeAssignedRole NodeRoleChangeUnionType = "NodeRoleChange_NodeAssignedRole"
)

type NodeRoleChangeUnion struct {
	NodeRoleChange                 *NodeRoleChange                 `queryParam:"inline,name=NodeRoleChange"`
	NodeRoleChangeNodeAssignedRole *NodeRoleChangeNodeAssignedRole `queryParam:"inline,name=NodeRoleChange"`

	Type NodeRoleChangeUnionType
}

func CreateNodeRoleChangeUnionNodeRoleChange(nodeRoleChange NodeRoleChange) NodeRoleChangeUnion {
	typ := NodeRoleChangeUnionTypeNodeRoleChange

	return NodeRoleChangeUnion{
		NodeRoleChange: &nodeRoleChange,
		Type:           typ,
	}
}

func CreateNodeRoleChangeUnionNodeRoleChangeNodeAssignedRole(nodeRoleChangeNodeAssignedRole NodeRoleChangeNodeAssignedRole) NodeRoleChangeUnion {
	typ := NodeRoleChangeUnionTypeNodeRoleChangeNodeAssignedRole

	return NodeRoleChangeUnion{
		NodeRoleChangeNodeAssignedRole: &nodeRoleChangeNodeAssignedRole,
		Type:                           typ,
	}
}

func (u *NodeRoleChangeUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var nodeRoleChangeNodeAssignedRole NodeRoleChangeNodeAssignedRole = NodeRoleChangeNodeAssignedRole{}
	if err := utils.UnmarshalJSON(data, &nodeRoleChangeNodeAssignedRole, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  NodeRoleChangeUnionTypeNodeRoleChangeNodeAssignedRole,
			Value: &nodeRoleChangeNodeAssignedRole,
		})
	}

	var nodeRoleChange NodeRoleChange = NodeRoleChange{}
	if err := utils.UnmarshalJSON(data, &nodeRoleChange, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  NodeRoleChangeUnionTypeNodeRoleChange,
			Value: &nodeRoleChange,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for NodeRoleChangeUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for NodeRoleChangeUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(NodeRoleChangeUnionType)
	switch best.Type {
	case NodeRoleChangeUnionTypeNodeRoleChangeNodeAssignedRole:
		u.NodeRoleChangeNodeAssignedRole = best.Value.(*NodeRoleChangeNodeAssignedRole)
		return nil
	case NodeRoleChangeUnionTypeNodeRoleChange:
		u.NodeRoleChange = best.Value.(*NodeRoleChange)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for NodeRoleChangeUnion", string(data))
}

func (u NodeRoleChangeUnion) MarshalJSON() ([]byte, error) {
	if u.NodeRoleChange != nil {
		return utils.MarshalJSON(u.NodeRoleChange, "", true)
	}

	if u.NodeRoleChangeNodeAssignedRole != nil {
		return utils.MarshalJSON(u.NodeRoleChangeNodeAssignedRole, "", true)
	}

	return nil, errors.New("could not marshal union type NodeRoleChangeUnion: all fields are null")
}
