// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type NodeResp struct {
	// Socket address used by other nodes to connect to this node for RPC
	Addr          optionalnullable.OptionalNullable[string]        `json:"addr,omitempty"`
	DataPartition optionalnullable.OptionalNullable[FreeSpaceResp] `json:"dataPartition,omitempty"`
	// Whether this node is part of an older layout version and is draining data.
	Draining bool `json:"draining"`
	// Garage version
	GarageVersion optionalnullable.OptionalNullable[string] `json:"garageVersion,omitempty"`
	// Hostname of the node
	Hostname optionalnullable.OptionalNullable[string] `json:"hostname,omitempty"`
	// Full-length node identifier
	ID string `json:"id"`
	// Whether this node is connected in the cluster
	IsUp bool `json:"isUp"`
	// For disconnected nodes, the number of seconds since last contact,
	// or `null` if no contact was established since Garage restarted.
	LastSeenSecsAgo   optionalnullable.OptionalNullable[int64]            `json:"lastSeenSecsAgo,omitempty"`
	MetadataPartition optionalnullable.OptionalNullable[FreeSpaceResp]    `json:"metadataPartition,omitempty"`
	Role              optionalnullable.OptionalNullable[NodeAssignedRole] `json:"role,omitempty"`
}

func (n *NodeResp) GetAddr() optionalnullable.OptionalNullable[string] {
	if n == nil {
		return nil
	}
	return n.Addr
}

func (n *NodeResp) GetDataPartition() optionalnullable.OptionalNullable[FreeSpaceResp] {
	if n == nil {
		return nil
	}
	return n.DataPartition
}

func (n *NodeResp) GetDraining() bool {
	if n == nil {
		return false
	}
	return n.Draining
}

func (n *NodeResp) GetGarageVersion() optionalnullable.OptionalNullable[string] {
	if n == nil {
		return nil
	}
	return n.GarageVersion
}

func (n *NodeResp) GetHostname() optionalnullable.OptionalNullable[string] {
	if n == nil {
		return nil
	}
	return n.Hostname
}

func (n *NodeResp) GetID() string {
	if n == nil {
		return ""
	}
	return n.ID
}

func (n *NodeResp) GetIsUp() bool {
	if n == nil {
		return false
	}
	return n.IsUp
}

func (n *NodeResp) GetLastSeenSecsAgo() optionalnullable.OptionalNullable[int64] {
	if n == nil {
		return nil
	}
	return n.LastSeenSecsAgo
}

func (n *NodeResp) GetMetadataPartition() optionalnullable.OptionalNullable[FreeSpaceResp] {
	if n == nil {
		return nil
	}
	return n.MetadataPartition
}

func (n *NodeResp) GetRole() optionalnullable.OptionalNullable[NodeAssignedRole] {
	if n == nil {
		return nil
	}
	return n.Role
}
