// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/guilhem/garage-go/internal/utils"
)

type PreviewClusterLayoutChangesResponse2 struct {
	// Plain-text information about the layout computation
	// (do not try to parse this)
	Message   []string                 `json:"message"`
	NewLayout GetClusterLayoutResponse `json:"newLayout"`
}

func (p PreviewClusterLayoutChangesResponse2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PreviewClusterLayoutChangesResponse2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"message", "newLayout"}); err != nil {
		return err
	}
	return nil
}

func (p *PreviewClusterLayoutChangesResponse2) GetMessage() []string {
	if p == nil {
		return []string{}
	}
	return p.Message
}

func (p *PreviewClusterLayoutChangesResponse2) GetNewLayout() GetClusterLayoutResponse {
	if p == nil {
		return GetClusterLayoutResponse{}
	}
	return p.NewLayout
}

type PreviewClusterLayoutChangesResponse1 struct {
	// Error message indicating that the layout could not be computed
	// with the provided configuration
	Error string `json:"error"`
}

func (p PreviewClusterLayoutChangesResponse1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PreviewClusterLayoutChangesResponse1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"error"}); err != nil {
		return err
	}
	return nil
}

func (p *PreviewClusterLayoutChangesResponse1) GetError() string {
	if p == nil {
		return ""
	}
	return p.Error
}

type PreviewClusterLayoutChangesResponseUnionType string

const (
	PreviewClusterLayoutChangesResponseUnionTypePreviewClusterLayoutChangesResponse1 PreviewClusterLayoutChangesResponseUnionType = "PreviewClusterLayoutChangesResponse_1"
	PreviewClusterLayoutChangesResponseUnionTypePreviewClusterLayoutChangesResponse2 PreviewClusterLayoutChangesResponseUnionType = "PreviewClusterLayoutChangesResponse_2"
)

type PreviewClusterLayoutChangesResponseUnion struct {
	PreviewClusterLayoutChangesResponse1 *PreviewClusterLayoutChangesResponse1 `queryParam:"inline,name=PreviewClusterLayoutChangesResponse"`
	PreviewClusterLayoutChangesResponse2 *PreviewClusterLayoutChangesResponse2 `queryParam:"inline,name=PreviewClusterLayoutChangesResponse"`

	Type PreviewClusterLayoutChangesResponseUnionType
}

func CreatePreviewClusterLayoutChangesResponseUnionPreviewClusterLayoutChangesResponse1(previewClusterLayoutChangesResponse1 PreviewClusterLayoutChangesResponse1) PreviewClusterLayoutChangesResponseUnion {
	typ := PreviewClusterLayoutChangesResponseUnionTypePreviewClusterLayoutChangesResponse1

	return PreviewClusterLayoutChangesResponseUnion{
		PreviewClusterLayoutChangesResponse1: &previewClusterLayoutChangesResponse1,
		Type:                                 typ,
	}
}

func CreatePreviewClusterLayoutChangesResponseUnionPreviewClusterLayoutChangesResponse2(previewClusterLayoutChangesResponse2 PreviewClusterLayoutChangesResponse2) PreviewClusterLayoutChangesResponseUnion {
	typ := PreviewClusterLayoutChangesResponseUnionTypePreviewClusterLayoutChangesResponse2

	return PreviewClusterLayoutChangesResponseUnion{
		PreviewClusterLayoutChangesResponse2: &previewClusterLayoutChangesResponse2,
		Type:                                 typ,
	}
}

func (u *PreviewClusterLayoutChangesResponseUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var previewClusterLayoutChangesResponse2 PreviewClusterLayoutChangesResponse2 = PreviewClusterLayoutChangesResponse2{}
	if err := utils.UnmarshalJSON(data, &previewClusterLayoutChangesResponse2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PreviewClusterLayoutChangesResponseUnionTypePreviewClusterLayoutChangesResponse2,
			Value: &previewClusterLayoutChangesResponse2,
		})
	}

	var previewClusterLayoutChangesResponse1 PreviewClusterLayoutChangesResponse1 = PreviewClusterLayoutChangesResponse1{}
	if err := utils.UnmarshalJSON(data, &previewClusterLayoutChangesResponse1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PreviewClusterLayoutChangesResponseUnionTypePreviewClusterLayoutChangesResponse1,
			Value: &previewClusterLayoutChangesResponse1,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PreviewClusterLayoutChangesResponseUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PreviewClusterLayoutChangesResponseUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(PreviewClusterLayoutChangesResponseUnionType)
	switch best.Type {
	case PreviewClusterLayoutChangesResponseUnionTypePreviewClusterLayoutChangesResponse2:
		u.PreviewClusterLayoutChangesResponse2 = best.Value.(*PreviewClusterLayoutChangesResponse2)
		return nil
	case PreviewClusterLayoutChangesResponseUnionTypePreviewClusterLayoutChangesResponse1:
		u.PreviewClusterLayoutChangesResponse1 = best.Value.(*PreviewClusterLayoutChangesResponse1)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PreviewClusterLayoutChangesResponseUnion", string(data))
}

func (u PreviewClusterLayoutChangesResponseUnion) MarshalJSON() ([]byte, error) {
	if u.PreviewClusterLayoutChangesResponse1 != nil {
		return utils.MarshalJSON(u.PreviewClusterLayoutChangesResponse1, "", true)
	}

	if u.PreviewClusterLayoutChangesResponse2 != nil {
		return utils.MarshalJSON(u.PreviewClusterLayoutChangesResponse2, "", true)
	}

	return nil, errors.New("could not marshal union type PreviewClusterLayoutChangesResponseUnion: all fields are null")
}
