// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/guilhem/garage-go/internal/utils"
)

type RemoveBucketAliasRequest2 struct {
	AccessKeyID string `json:"accessKeyId"`
	LocalAlias  string `json:"localAlias"`
	BucketID    string `json:"bucketId"`
}

func (r RemoveBucketAliasRequest2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RemoveBucketAliasRequest2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"accessKeyId", "localAlias", "bucketId"}); err != nil {
		return err
	}
	return nil
}

func (r *RemoveBucketAliasRequest2) GetAccessKeyID() string {
	if r == nil {
		return ""
	}
	return r.AccessKeyID
}

func (r *RemoveBucketAliasRequest2) GetLocalAlias() string {
	if r == nil {
		return ""
	}
	return r.LocalAlias
}

func (r *RemoveBucketAliasRequest2) GetBucketID() string {
	if r == nil {
		return ""
	}
	return r.BucketID
}

type RemoveBucketAliasRequest1 struct {
	GlobalAlias string `json:"globalAlias"`
	BucketID    string `json:"bucketId"`
}

func (r RemoveBucketAliasRequest1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RemoveBucketAliasRequest1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"globalAlias", "bucketId"}); err != nil {
		return err
	}
	return nil
}

func (r *RemoveBucketAliasRequest1) GetGlobalAlias() string {
	if r == nil {
		return ""
	}
	return r.GlobalAlias
}

func (r *RemoveBucketAliasRequest1) GetBucketID() string {
	if r == nil {
		return ""
	}
	return r.BucketID
}

type RemoveBucketAliasRequestUnionType string

const (
	RemoveBucketAliasRequestUnionTypeRemoveBucketAliasRequest1 RemoveBucketAliasRequestUnionType = "RemoveBucketAliasRequest_1"
	RemoveBucketAliasRequestUnionTypeRemoveBucketAliasRequest2 RemoveBucketAliasRequestUnionType = "RemoveBucketAliasRequest_2"
)

type RemoveBucketAliasRequestUnion struct {
	RemoveBucketAliasRequest1 *RemoveBucketAliasRequest1 `queryParam:"inline,name=RemoveBucketAliasRequest"`
	RemoveBucketAliasRequest2 *RemoveBucketAliasRequest2 `queryParam:"inline,name=RemoveBucketAliasRequest"`

	Type RemoveBucketAliasRequestUnionType
}

func CreateRemoveBucketAliasRequestUnionRemoveBucketAliasRequest1(removeBucketAliasRequest1 RemoveBucketAliasRequest1) RemoveBucketAliasRequestUnion {
	typ := RemoveBucketAliasRequestUnionTypeRemoveBucketAliasRequest1

	return RemoveBucketAliasRequestUnion{
		RemoveBucketAliasRequest1: &removeBucketAliasRequest1,
		Type:                      typ,
	}
}

func CreateRemoveBucketAliasRequestUnionRemoveBucketAliasRequest2(removeBucketAliasRequest2 RemoveBucketAliasRequest2) RemoveBucketAliasRequestUnion {
	typ := RemoveBucketAliasRequestUnionTypeRemoveBucketAliasRequest2

	return RemoveBucketAliasRequestUnion{
		RemoveBucketAliasRequest2: &removeBucketAliasRequest2,
		Type:                      typ,
	}
}

func (u *RemoveBucketAliasRequestUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var removeBucketAliasRequest2 RemoveBucketAliasRequest2 = RemoveBucketAliasRequest2{}
	if err := utils.UnmarshalJSON(data, &removeBucketAliasRequest2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RemoveBucketAliasRequestUnionTypeRemoveBucketAliasRequest2,
			Value: &removeBucketAliasRequest2,
		})
	}

	var removeBucketAliasRequest1 RemoveBucketAliasRequest1 = RemoveBucketAliasRequest1{}
	if err := utils.UnmarshalJSON(data, &removeBucketAliasRequest1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RemoveBucketAliasRequestUnionTypeRemoveBucketAliasRequest1,
			Value: &removeBucketAliasRequest1,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for RemoveBucketAliasRequestUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for RemoveBucketAliasRequestUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(RemoveBucketAliasRequestUnionType)
	switch best.Type {
	case RemoveBucketAliasRequestUnionTypeRemoveBucketAliasRequest2:
		u.RemoveBucketAliasRequest2 = best.Value.(*RemoveBucketAliasRequest2)
		return nil
	case RemoveBucketAliasRequestUnionTypeRemoveBucketAliasRequest1:
		u.RemoveBucketAliasRequest1 = best.Value.(*RemoveBucketAliasRequest1)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RemoveBucketAliasRequestUnion", string(data))
}

func (u RemoveBucketAliasRequestUnion) MarshalJSON() ([]byte, error) {
	if u.RemoveBucketAliasRequest1 != nil {
		return utils.MarshalJSON(u.RemoveBucketAliasRequest1, "", true)
	}

	if u.RemoveBucketAliasRequest2 != nil {
		return utils.MarshalJSON(u.RemoveBucketAliasRequest2, "", true)
	}

	return nil, errors.New("could not marshal union type RemoveBucketAliasRequestUnion: all fields are null")
}
