// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ScrubCommand string

const (
	ScrubCommandStart  ScrubCommand = "start"
	ScrubCommandPause  ScrubCommand = "pause"
	ScrubCommandResume ScrubCommand = "resume"
	ScrubCommandCancel ScrubCommand = "cancel"
)

func (e ScrubCommand) ToPointer() *ScrubCommand {
	return &e
}
func (e *ScrubCommand) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "start":
		fallthrough
	case "pause":
		fallthrough
	case "resume":
		fallthrough
	case "cancel":
		*e = ScrubCommand(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ScrubCommand: %v", v)
	}
}
