// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type UpdateClusterLayoutRequest struct {
	Parameters optionalnullable.OptionalNullable[LayoutParameters] `json:"parameters,omitempty"`
	// New node roles to assign or remove in the cluster layout
	Roles []NodeRoleChangeUnion `json:"roles,omitempty"`
}

func (u *UpdateClusterLayoutRequest) GetParameters() optionalnullable.OptionalNullable[LayoutParameters] {
	if u == nil {
		return nil
	}
	return u.Parameters
}

func (u *UpdateClusterLayoutRequest) GetRoles() []NodeRoleChangeUnion {
	if u == nil {
		return nil
	}
	return u.Roles
}
