// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type UpdateBucketRequestBody struct {
	Quotas        optionalnullable.OptionalNullable[APIBucketQuotas]           `json:"quotas,omitempty"`
	WebsiteAccess optionalnullable.OptionalNullable[UpdateBucketWebsiteAccess] `json:"websiteAccess,omitempty"`
}

func (u *UpdateBucketRequestBody) GetQuotas() optionalnullable.OptionalNullable[APIBucketQuotas] {
	if u == nil {
		return nil
	}
	return u.Quotas
}

func (u *UpdateBucketRequestBody) GetWebsiteAccess() optionalnullable.OptionalNullable[UpdateBucketWebsiteAccess] {
	if u == nil {
		return nil
	}
	return u.WebsiteAccess
}
