// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type UpdateBucketWebsiteAccess struct {
	Enabled       bool                                      `json:"enabled"`
	ErrorDocument optionalnullable.OptionalNullable[string] `json:"errorDocument,omitempty"`
	IndexDocument optionalnullable.OptionalNullable[string] `json:"indexDocument,omitempty"`
}

func (u *UpdateBucketWebsiteAccess) GetEnabled() bool {
	if u == nil {
		return false
	}
	return u.Enabled
}

func (u *UpdateBucketWebsiteAccess) GetErrorDocument() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.ErrorDocument
}

func (u *UpdateBucketWebsiteAccess) GetIndexDocument() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.IndexDocument
}
