// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/internal/utils"
	"github.com/guilhem/garage-go/optionalnullable"
	"time"
)

type UpdateAdminTokenRequestBody struct {
	// Expiration time and date, formatted according to RFC 3339
	Expiration optionalnullable.OptionalNullable[time.Time] `json:"expiration,omitempty"`
	// Name of the admin API token
	Name optionalnullable.OptionalNullable[string] `json:"name,omitempty"`
	// Set the admin token to never expire
	NeverExpires *bool `json:"neverExpires,omitempty"`
	// Scope of the admin API token, a list of admin endpoint names (such as
	// `GetClusterStatus`, etc), or the special value `*` to allow all
	// admin endpoints. **WARNING:** Granting a scope of `CreateAdminToken` or
	// `UpdateAdminToken` trivially allows for privilege escalation, and is thus
	// functionnally equivalent to granting a scope of `*`.
	Scope optionalnullable.OptionalNullable[[]string] `json:"scope,omitempty"`
}

func (u UpdateAdminTokenRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAdminTokenRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAdminTokenRequestBody) GetExpiration() optionalnullable.OptionalNullable[time.Time] {
	if u == nil {
		return nil
	}
	return u.Expiration
}

func (u *UpdateAdminTokenRequestBody) GetName() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateAdminTokenRequestBody) GetNeverExpires() *bool {
	if u == nil {
		return nil
	}
	return u.NeverExpires
}

func (u *UpdateAdminTokenRequestBody) GetScope() optionalnullable.OptionalNullable[[]string] {
	if u == nil {
		return nil
	}
	return u.Scope
}
