// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/guilhem/garage-go/optionalnullable"
)

type WorkerInfoResp struct {
	ConsecutiveErrors int64                                              `json:"consecutiveErrors"`
	Errors            int64                                              `json:"errors"`
	Freeform          []string                                           `json:"freeform"`
	ID                int64                                              `json:"id"`
	LastError         optionalnullable.OptionalNullable[WorkerLastError] `json:"lastError,omitempty"`
	Name              string                                             `json:"name"`
	PersistentErrors  optionalnullable.OptionalNullable[int64]           `json:"persistentErrors,omitempty"`
	Progress          optionalnullable.OptionalNullable[string]          `json:"progress,omitempty"`
	QueueLength       optionalnullable.OptionalNullable[int64]           `json:"queueLength,omitempty"`
	State             WorkerStateRespUnion                               `json:"state"`
	Tranquility       optionalnullable.OptionalNullable[int]             `json:"tranquility,omitempty"`
}

func (w *WorkerInfoResp) GetConsecutiveErrors() int64 {
	if w == nil {
		return 0
	}
	return w.ConsecutiveErrors
}

func (w *WorkerInfoResp) GetErrors() int64 {
	if w == nil {
		return 0
	}
	return w.Errors
}

func (w *WorkerInfoResp) GetFreeform() []string {
	if w == nil {
		return []string{}
	}
	return w.Freeform
}

func (w *WorkerInfoResp) GetID() int64 {
	if w == nil {
		return 0
	}
	return w.ID
}

func (w *WorkerInfoResp) GetLastError() optionalnullable.OptionalNullable[WorkerLastError] {
	if w == nil {
		return nil
	}
	return w.LastError
}

func (w *WorkerInfoResp) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *WorkerInfoResp) GetPersistentErrors() optionalnullable.OptionalNullable[int64] {
	if w == nil {
		return nil
	}
	return w.PersistentErrors
}

func (w *WorkerInfoResp) GetProgress() optionalnullable.OptionalNullable[string] {
	if w == nil {
		return nil
	}
	return w.Progress
}

func (w *WorkerInfoResp) GetQueueLength() optionalnullable.OptionalNullable[int64] {
	if w == nil {
		return nil
	}
	return w.QueueLength
}

func (w *WorkerInfoResp) GetState() WorkerStateRespUnion {
	if w == nil {
		return WorkerStateRespUnion{}
	}
	return w.State
}

func (w *WorkerInfoResp) GetTranquility() optionalnullable.OptionalNullable[int] {
	if w == nil {
		return nil
	}
	return w.Tranquility
}
