// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WorkerLastError struct {
	Message string `json:"message"`
	SecsAgo int64  `json:"secsAgo"`
}

func (w *WorkerLastError) GetMessage() string {
	if w == nil {
		return ""
	}
	return w.Message
}

func (w *WorkerLastError) GetSecsAgo() int64 {
	if w == nil {
		return 0
	}
	return w.SecsAgo
}
