// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/guilhem/garage-go/internal/utils"
)

type WorkerStateRespDone string

const (
	WorkerStateRespDoneDone WorkerStateRespDone = "done"
)

func (e WorkerStateRespDone) ToPointer() *WorkerStateRespDone {
	return &e
}
func (e *WorkerStateRespDone) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "done":
		*e = WorkerStateRespDone(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WorkerStateRespDone: %v", v)
	}
}

type WorkerStateRespIdle string

const (
	WorkerStateRespIdleIdle WorkerStateRespIdle = "idle"
)

func (e WorkerStateRespIdle) ToPointer() *WorkerStateRespIdle {
	return &e
}
func (e *WorkerStateRespIdle) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "idle":
		*e = WorkerStateRespIdle(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WorkerStateRespIdle: %v", v)
	}
}

type Throttled struct {
	DurationSecs float32 `json:"durationSecs"`
}

func (t Throttled) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Throttled) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"durationSecs"}); err != nil {
		return err
	}
	return nil
}

func (t *Throttled) GetDurationSecs() float32 {
	if t == nil {
		return 0.0
	}
	return t.DurationSecs
}

type WorkerStateResp struct {
	Throttled Throttled `json:"throttled"`
}

func (w WorkerStateResp) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkerStateResp) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, []string{"throttled"}); err != nil {
		return err
	}
	return nil
}

func (w *WorkerStateResp) GetThrottled() Throttled {
	if w == nil {
		return Throttled{}
	}
	return w.Throttled
}

type WorkerStateRespBusy string

const (
	WorkerStateRespBusyBusy WorkerStateRespBusy = "busy"
)

func (e WorkerStateRespBusy) ToPointer() *WorkerStateRespBusy {
	return &e
}
func (e *WorkerStateRespBusy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "busy":
		*e = WorkerStateRespBusy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WorkerStateRespBusy: %v", v)
	}
}

type WorkerStateRespUnionType string

const (
	WorkerStateRespUnionTypeWorkerStateRespBusy WorkerStateRespUnionType = "WorkerStateResp_Busy"
	WorkerStateRespUnionTypeWorkerStateResp     WorkerStateRespUnionType = "WorkerStateResp"
	WorkerStateRespUnionTypeWorkerStateRespIdle WorkerStateRespUnionType = "WorkerStateResp_Idle"
	WorkerStateRespUnionTypeWorkerStateRespDone WorkerStateRespUnionType = "WorkerStateResp_Done"
)

type WorkerStateRespUnion struct {
	WorkerStateRespBusy *WorkerStateRespBusy `queryParam:"inline,name=WorkerStateResp"`
	WorkerStateResp     *WorkerStateResp     `queryParam:"inline,name=WorkerStateResp"`
	WorkerStateRespIdle *WorkerStateRespIdle `queryParam:"inline,name=WorkerStateResp"`
	WorkerStateRespDone *WorkerStateRespDone `queryParam:"inline,name=WorkerStateResp"`

	Type WorkerStateRespUnionType
}

func CreateWorkerStateRespUnionWorkerStateRespBusy(workerStateRespBusy WorkerStateRespBusy) WorkerStateRespUnion {
	typ := WorkerStateRespUnionTypeWorkerStateRespBusy

	return WorkerStateRespUnion{
		WorkerStateRespBusy: &workerStateRespBusy,
		Type:                typ,
	}
}

func CreateWorkerStateRespUnionWorkerStateResp(workerStateResp WorkerStateResp) WorkerStateRespUnion {
	typ := WorkerStateRespUnionTypeWorkerStateResp

	return WorkerStateRespUnion{
		WorkerStateResp: &workerStateResp,
		Type:            typ,
	}
}

func CreateWorkerStateRespUnionWorkerStateRespIdle(workerStateRespIdle WorkerStateRespIdle) WorkerStateRespUnion {
	typ := WorkerStateRespUnionTypeWorkerStateRespIdle

	return WorkerStateRespUnion{
		WorkerStateRespIdle: &workerStateRespIdle,
		Type:                typ,
	}
}

func CreateWorkerStateRespUnionWorkerStateRespDone(workerStateRespDone WorkerStateRespDone) WorkerStateRespUnion {
	typ := WorkerStateRespUnionTypeWorkerStateRespDone

	return WorkerStateRespUnion{
		WorkerStateRespDone: &workerStateRespDone,
		Type:                typ,
	}
}

func (u *WorkerStateRespUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var workerStateResp WorkerStateResp = WorkerStateResp{}
	if err := utils.UnmarshalJSON(data, &workerStateResp, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  WorkerStateRespUnionTypeWorkerStateResp,
			Value: &workerStateResp,
		})
	}

	var workerStateRespBusy WorkerStateRespBusy = WorkerStateRespBusy("")
	if err := utils.UnmarshalJSON(data, &workerStateRespBusy, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  WorkerStateRespUnionTypeWorkerStateRespBusy,
			Value: &workerStateRespBusy,
		})
	}

	var workerStateRespIdle WorkerStateRespIdle = WorkerStateRespIdle("")
	if err := utils.UnmarshalJSON(data, &workerStateRespIdle, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  WorkerStateRespUnionTypeWorkerStateRespIdle,
			Value: &workerStateRespIdle,
		})
	}

	var workerStateRespDone WorkerStateRespDone = WorkerStateRespDone("")
	if err := utils.UnmarshalJSON(data, &workerStateRespDone, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  WorkerStateRespUnionTypeWorkerStateRespDone,
			Value: &workerStateRespDone,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for WorkerStateRespUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for WorkerStateRespUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(WorkerStateRespUnionType)
	switch best.Type {
	case WorkerStateRespUnionTypeWorkerStateResp:
		u.WorkerStateResp = best.Value.(*WorkerStateResp)
		return nil
	case WorkerStateRespUnionTypeWorkerStateRespBusy:
		u.WorkerStateRespBusy = best.Value.(*WorkerStateRespBusy)
		return nil
	case WorkerStateRespUnionTypeWorkerStateRespIdle:
		u.WorkerStateRespIdle = best.Value.(*WorkerStateRespIdle)
		return nil
	case WorkerStateRespUnionTypeWorkerStateRespDone:
		u.WorkerStateRespDone = best.Value.(*WorkerStateRespDone)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for WorkerStateRespUnion", string(data))
}

func (u WorkerStateRespUnion) MarshalJSON() ([]byte, error) {
	if u.WorkerStateRespBusy != nil {
		return utils.MarshalJSON(u.WorkerStateRespBusy, "", true)
	}

	if u.WorkerStateResp != nil {
		return utils.MarshalJSON(u.WorkerStateResp, "", true)
	}

	if u.WorkerStateRespIdle != nil {
		return utils.MarshalJSON(u.WorkerStateRespIdle, "", true)
	}

	if u.WorkerStateRespDone != nil {
		return utils.MarshalJSON(u.WorkerStateRespDone, "", true)
	}

	return nil, errors.New("could not marshal union type WorkerStateRespUnion: all fields are null")
}
