// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/guilhem/garage-go/internal/utils"
)

// ZoneRedundancyEnum - Partitions must be replicated in as many zones as possible:
// as many zones as there are replicas, if there are enough distinct
// zones, or at least one in each zone otherwise.
type ZoneRedundancyEnum string

const (
	ZoneRedundancyEnumMaximum ZoneRedundancyEnum = "maximum"
)

func (e ZoneRedundancyEnum) ToPointer() *ZoneRedundancyEnum {
	return &e
}
func (e *ZoneRedundancyEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "maximum":
		*e = ZoneRedundancyEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ZoneRedundancyEnum: %v", v)
	}
}

// ZoneRedundancy - Partitions must be replicated in at least this number of
// distinct zones.
type ZoneRedundancy struct {
	// Partitions must be replicated in at least this number of
	// distinct zones.
	AtLeast int64 `json:"atLeast"`
}

func (z ZoneRedundancy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(z, "", false)
}

func (z *ZoneRedundancy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &z, "", false, []string{"atLeast"}); err != nil {
		return err
	}
	return nil
}

func (z *ZoneRedundancy) GetAtLeast() int64 {
	if z == nil {
		return 0
	}
	return z.AtLeast
}

type ZoneRedundancyUnionType string

const (
	ZoneRedundancyUnionTypeZoneRedundancy     ZoneRedundancyUnionType = "ZoneRedundancy"
	ZoneRedundancyUnionTypeZoneRedundancyEnum ZoneRedundancyUnionType = "ZoneRedundancy_enum"
)

type ZoneRedundancyUnion struct {
	ZoneRedundancy     *ZoneRedundancy     `queryParam:"inline,name=ZoneRedundancy"`
	ZoneRedundancyEnum *ZoneRedundancyEnum `queryParam:"inline,name=ZoneRedundancy"`

	Type ZoneRedundancyUnionType
}

func CreateZoneRedundancyUnionZoneRedundancy(zoneRedundancy ZoneRedundancy) ZoneRedundancyUnion {
	typ := ZoneRedundancyUnionTypeZoneRedundancy

	return ZoneRedundancyUnion{
		ZoneRedundancy: &zoneRedundancy,
		Type:           typ,
	}
}

func CreateZoneRedundancyUnionZoneRedundancyEnum(zoneRedundancyEnum ZoneRedundancyEnum) ZoneRedundancyUnion {
	typ := ZoneRedundancyUnionTypeZoneRedundancyEnum

	return ZoneRedundancyUnion{
		ZoneRedundancyEnum: &zoneRedundancyEnum,
		Type:               typ,
	}
}

func (u *ZoneRedundancyUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var zoneRedundancy ZoneRedundancy = ZoneRedundancy{}
	if err := utils.UnmarshalJSON(data, &zoneRedundancy, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ZoneRedundancyUnionTypeZoneRedundancy,
			Value: &zoneRedundancy,
		})
	}

	var zoneRedundancyEnum ZoneRedundancyEnum = ZoneRedundancyEnum("")
	if err := utils.UnmarshalJSON(data, &zoneRedundancyEnum, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ZoneRedundancyUnionTypeZoneRedundancyEnum,
			Value: &zoneRedundancyEnum,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ZoneRedundancyUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ZoneRedundancyUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ZoneRedundancyUnionType)
	switch best.Type {
	case ZoneRedundancyUnionTypeZoneRedundancy:
		u.ZoneRedundancy = best.Value.(*ZoneRedundancy)
		return nil
	case ZoneRedundancyUnionTypeZoneRedundancyEnum:
		u.ZoneRedundancyEnum = best.Value.(*ZoneRedundancyEnum)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ZoneRedundancyUnion", string(data))
}

func (u ZoneRedundancyUnion) MarshalJSON() ([]byte, error) {
	if u.ZoneRedundancy != nil {
		return utils.MarshalJSON(u.ZoneRedundancy, "", true)
	}

	if u.ZoneRedundancyEnum != nil {
		return utils.MarshalJSON(u.ZoneRedundancyEnum, "", true)
	}

	return nil, errors.New("could not marshal union type ZoneRedundancyUnion: all fields are null")
}
